### ISSUE TITLE
Crush while connecting my FlsunQ5 printer in a Surface PRO 7

### ISSUE THREAD

**Issue by SquintPlug7** [repetier/Repetier-Firmware#1090]
It crush every itme i m pressing the button "connect" idk why... i dont think it is an app too heavy to handle for my pc ... it s a surface pro 7 and to be honest it can handle much heavier app

**Comment by repetier** [comment]
Firmware runs on printers not on surface and I don't think you have installed it since it has no connect button.

So what software are you talking about?
If you mean  Repetier-Server make sure you have not version 1.4.4 which has an issue with non utf-8 answers that can cause crash on connect.

**Comment by SquintPlug7** [comment]
Oh thankyou, i was meaning repetier Host by the way not the server.... Now i ve just checked and i have the 1.4.6 because the 1.4.4 gives me problems... but i think also1.4.6 gives me them anyway.
The version of repetier host is the last one (2.3.1) and after configurate my printer correctly when i press the "cable button " to connect it with serial connection it crush... every single time

**Comment by repetier** [comment]
Open the web interface of  Repetier-Server ( http://localhost:3344 ) and go to check updates. There is a autoupdater that will upgrade when clicked.

Since we install server by default that might in deed be the case.
