### ISSUE TITLE
1.0.5 dev incorrect processed PID calibration g-code  M303

### ISSUE THREAD

**Issue by Klutae** [repetier/Repetier-Firmware#1093]
M303 E0 S200 C8 - worked correct, but  M303 E-1 S70 C8 not run calibate heating bed. Instead, it performs M303 E0. Tersted on anycubic kossel plus (trigorilla 1.4)

**Comment by Klutae** [comment]
Sorry, M303 P1 S70 C8 - correct command for repetier

**Comment by repetier** [comment]
Assuming it worked with correct command I close the issue.
