### ISSUE TITLE
Proper Pronunciation of Repetier

### ISSUE THREAD

**Issue by flickerfly** [repetier/Repetier-Firmware#140]
I've been trying to figure out what the proper pronunciation of Repetier is, but I can't even determine for certain what language it is. The debate rages on.

I was hoping to find something like Linus Torvald's classic audio recording telling folks how Linux is pronounced. Could we get something like from Marcus Littwin? 

http://www.paul.sladen.org/pronunciation/torvalds-says-linux.mp3

Thanks!

**Comment by rynbrk** [comment]
Can we get audio on this?
