### ISSUE TITLE
Auto level doesn't work on Rostock delta printers

### ISSUE THREAD

**Issue by 626Pilot** [repetier/Repetier-Firmware#167]
Two people have tried running the dev code for autolevel on Rostock MAX printers with RAMBo boards. One had a mechanical endstop switch and the other (me) a Hall-O probe. In both cases, after running the bed leveling G-code described in the instructions, the computed plane of the build platform was erroneously tilted about both the X and Y axes. As a result, moving from the center of the build platform results in the nozzle either lifting off the platform (X- and Y- directions) or trying to dig into the platform (X+ and Y+ directions.) Deviation is as high as several millimeters at the edge.

We had another developer looking at the issue but he hasn't been able to figure it out. Do you know what might be causing this?

**Comment by joeyrodrigue** [comment]
Have Rostock MAX V3.
Could not get a 150 mm ring to stick at the XY part of circle using Simplify3D to print.
Repeated G29 calibrations did not help.
Took the same STL file into MatterHackers Matter Control 1.6, did one calibration and worked perfectly.
