### ISSUE TITLE
Support for dual x-carriage

### ISSUE THREAD

**Issue by Kenzu** [repetier/Repetier-Firmware#224]
Hey

I'am rebuilding my old Prusa i2 to dual x-carriage, but that means i have to use marlin, and i don't like marlin for multi-extruder. No estep per extruder :-(
See picture here https://plus.google.com/101171137569571196735/posts/iqNn4rXoMWh
Can you add support for dual x-carriage in repetier?

See line 168 here for more info https://github.com/ErikZalm/Marlin/blob/Marlin_v1/Marlin/Configuration_adv.h

Thanks

Jesper

**Comment by Kulitorum** [comment]
Any progress on this? - I think this is my only viable option to get dual-extrution working properly.

**Comment by gui7vaz** [comment]
Hello.
This feature will be awesome!
This printer is doing this:
https://www.bcn3dtechnologies.com/en/catalog/bcn3d-sigma/
Here is the page for the modified marlin firmware.
https://github.com/BCN3D/BCN3DSigma-Firmware

**Comment by repetier** [comment]
Yes, since a few weeks this is possible. You need the development version and in config tool you can select dual x axis and just select a second motor driver for the right extruder/axis.

**Comment by alfredanil** [comment]
Would it be possible to mount the laser diode module or spindle motor on the second X axis?

**Comment by repetier** [comment]
Logic is T1 selects the right carriage. What it contains should be independent. But you must define 2 Extruder! If it is not a extruder select thermistor not used to prevent errors like dry run, but then it should do the trick.

**Comment by alfredanil** [comment]
Still, the extruder would be dead weight or viceversa thereby adding inertia load to the Y-axis (if X is mounted on dual Y). Would be better if there is a tool holder for various applications.

**Comment by repetier** [comment]
I did not say to put a extruder on it. You must have configured 2 extruder for it to work but it must not have extruder functionality. YOu can fake extruder on software side by selecting a dummy themistor/heater.

**Comment by alfredanil** [comment]
Yes, I got your point. What I meant was having FFF on one X and laser or milling on the other X, does offer multi functionality but it also adds additional weight when used in either of the modes. I was only suggesting a tool holder for holding FFF or laser or spindle, so that the X carries only the tool that is necessary.

**Comment by repetier** [comment]
Sure a tool holder makes it easier to switch without weight penalty:-) But that is up to hardware producer.

**Comment by pbrgle1** [comment]
Hi! I have 3 questions. I want to test repetier on my dual x carriage printer - comming from marlin btw.

- How can i set a manual X1 zero (home) position (my endstop is actually at cca. -50mm)
- How to set the distance between nozzles
- How to set endstop for X2 (connected to X_Max pin)

**Comment by repetier** [comment]
@pbrgle1 Thats very easy. Both extruders have a variable x offset. These are the offsets to the x = 0 on table. So E0 would need -50 and E1 something like 250. If set correctly after homing T0 is at x=0 and T1 should move E1 to the same position.

**Comment by pbrgle1** [comment]
alles klar! I´ll do some tests and let you know how it compares to marlin.

I've been using dual x carriage for the past 1-2 years with marlin and i just noticed that repetier also hast this option. Maybe i'll switch to ARM based controllers.

**Comment by repetier** [comment]
Implemented.
