### ISSUE TITLE
Baby stepping

### ISSUE THREAD

**Issue by mhackney** [repetier/Repetier-Firmware#274]
I'm not sure how the baby stepping feature is supposed to work. I watched the Marlin baby step video and attempted to change Z height during the 1st layer from Repetier Host. My Rostock sped up extremely fast and made a complete perimeter of the part, then slowed down. I did not observe a change in Z. Is this a bug or not understanding the feature?

**Comment by tcurdt** [comment]
I am not getting this feature either. I adjust the z with babystepping, then home the machine and it's back to 0.

**Comment by repetier** [comment]
Sure homing will delete it. That never was the intention. It is to make current print stick if you see it fails already on skirt/brim. If it is a permanent error you need to calibrate homing position.

**Comment by tcurdt** [comment]
@repetier I guess I was just hoping for a "store as z0" in the same menu. But seems this really is under configuration.

**Comment by repetier** [comment]
Store z=0 is only possible for z max homing as you then simply can change z length so z=0 matches.

For z min homing the homing position is per definition 0. If you have bed coating enabled you can set that to change z=0 under some conditions.

**Comment by tcurdt** [comment]
It's a delta with z max homing. It seems `M251 S2` does what I was looking for.

**Comment by repetier** [comment]
Did not remember that command, but you are right and it is not limited to deltas, only to z max homing.
