### ISSUE TITLE
Extruder Rotation direction wrong when using two extruders with advance activated

### ISSUE THREAD

**Issue by simonkuehling** [repetier/Repetier-Firmware#315]
Hi Roland,

i'd like to get back to this issue once more - which we already discussed ealier this year:

If i am using two extruders, both with activated advance factor (`EXT0_ADVANCE_L 15.0f`, `EXT1_ADVANCE_L 15.0f`), **the first extruder will turn in the wrong direction** when running the following gcode directly after a fresh microcontroller reset:

```
T1
G91
G1 E5 F30            --> right extruder turns forward as it is supposed to
G90
T0
G91
G1 E5 F30            --> left extruder turns BACKWARDS!?
G90
```

This may have something to do with checking if the current extruder move needs advance or not (`isXYZMove()`). As far as i can tell this is only behaving this way when using the extruders in this order (T1, T0).

Could you or someone else try to verify this issue on another dual extruder setup? We are pulling our hair out over this for some time already :-)

**Comment by simonkuehling** [comment]
Eureka!

I finally found the reason. I missed one tiny line of your fix: I did not remove <code>static int8_t extruderLastDirection = 0;</code> from the beginning of <code>ISR(EXTRUDER_TIMER_VECTOR)</code>

So <code>resetExtruderDirection()</code> was basically not functioning :-)

Now it is working just fine. Just wanted to keep you updated regarding our chat at euromold'14...

**Comment by repetier** [comment]
Great to hear this was not my fault:-)

I assume that the advance algorithm now is also working with the right direction? Or what exactly was the problem with it. With all these wishes I get I'm a bit confused.

**Comment by simonkuehling** [comment]
The final conclusion from my side, to sum things up: The fix you introduced does indeed work (if applied in its whole, my fault).
I am now endurance testing the advance functionality with both extruders, now that it is working again - yay! :-)
