### ISSUE TITLE
0.92 Compile error under Arduino 1.5.7, and possible fix 

### ISSUE THREAD

**Issue by Paul--W** [repetier/Repetier-Firmware#330]
There are 6 compile errors like this under Arduino 1.5.7:

ui.cpp: In member function 'void UIDisplay::adjustMenuPos()':
ui.cpp:2114:47: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
     uint8_t mtype = HAL::readFlashByte((const prog_char*)&(men->menuType));

My fix was to add the following to the top of ui.cpp:
# define prog_char char

I am not a C expert so please confirm if this is right...
Now it complies clean, with one low memory warning:

Sketch uses 118,190 bytes (45%) of program storage space. Maximum is 258,048 bytes.
Global variables use 7,026 bytes (85%) of dynamic memory, leaving 1,166 bytes for local variables. Maximum is 8,192 bytes.
Low memory available, stability problems may occur.

Thanks!

**Comment by lcyrax** [comment]
thanks！it help a lot ！
it work for me too！
