### ISSUE TITLE
KILL button does not "kill" printer and not turn off PWR_ON signal

### ISSUE THREAD

**Issue by sp3swj** [repetier/Repetier-Firmware#339]
Repetier 0,92 + Ramps + FULL Graphic LCD  128x64.

After press KILL button under LCD  not reset signal PWR_ON to  "OFF" state.

Just restart  printer to startup.

After KILL - printer should be  "FROZEN".  ( in my opinion)

**Comment by repetier** [comment]
Closing for double issue.
