### ISSUE TITLE
4 extruders + lcd display = error compile

### ISSUE THREAD

**Issue by internet-conception** [repetier/Repetier-Firmware#341]
Hi,

In the uimenu.h file there is at line 253 :
 #if (NUM_EXTRUDER == 3 && MIXING_EXTRUDER == 0 && !HAVE_HEATED_BED) || (NUM_EXTRUDER==2 && MIXING_EXTRUDER == 0 && HAVE_HEATED_BED==true)

I had to change this (heigher or equal) :
 #if (NUM_EXTRUDER >= 3 && MIXING_EXTRUDER == 0 && !HAVE_HEATED_BED) || (NUM_EXTRUDER==2 && MIXING_EXTRUDER == 0 && HAVE_HEATED_BED==true)

It let me compile without error but it wont display a new screen with the 4th extruder temperature, etc...

I have an azteeg X3 pro + viki lcd + kraken 4 heads my firmware is based on the online firmware tool.

I know it's not a typical setup but the number of screen menu is dependant of the extruder num right ?

Hope to see an update soon ;o)
Thank's a lot and a big "congratulation" for your wonderfull job !!!

**Comment by euanfoster** [comment]
Hey there,

I have the exact same hardware set up and was wondering if there had been any progress on this or has someone managed to modify the firmware themselves?

**Comment by repetier** [comment]
Fixed
