### ISSUE TITLE
X homing retest in wrong direction with 2+ extruders

### ISSUE THREAD

**Issue by internet-conception** [repetier/Repetier-Firmware#344]
hi,

I try to setup my kraken (4 hotends) vith repetier firmware 0.92.

When I set 2 extruders in config.h it work as expected.
But when I set it up to 3 or 4 extruders the "retest" function have a strange behavior...
I think the "#define ENDSTOP_X_BACK_MOVE 5" parameter is not divide by two and do all the lenght in the opposite way. Also the "#define ENDSTOP_X_BACK_ON_HOME" become inactive.

Is it something easy to fix ?

Thank's a lot ;o)

Ps: Z & Y work's well with 4 extruders

**Comment by repetier** [comment]
I'm not sure it is an error since your description is vague. What is a strange behaviour for you?

You need to understand how multiple extruders are handled. If you have 2 extruders T0 with x offset 0 and T1 with offset 20 you should expect the extruder to go after homing 20mm additional to the right in order to select extruder 0 and still allow extruder 1 to be selected. This does not change for offsets -10 and 10. Is that your strange behaviour?

**Comment by internet-conception** [comment]
I understand what you mean and it look good ;o)
I'll try to change my hotend order and my mind too. But it make sense.

Happy to have a new direction to digg !
Thank's a lot as usual you are perfect.

**Comment by internet-conception** [comment]
I tried so many differents combinations... all with the same result :o(
I dont know what to do next...

Here is a video of the "strange behaviour" : https://www.youtube.com/watch?v=Qz2mgqU1WAE
Here is my config.h : http://pastebin.com/XT0qChMi
(of course #define NUM_EXTRUDER was set to 4)
Here a picture of my printer setup : https://faust.federelle.com/printer.jpg

Can you give a look at my printer setup? may be it will appear up to you at a glance ;)

btw: the 4 extruder's heater + tmp sensors work's well

**Comment by vinmicgra** [comment]
Hi, check the offsets: EXT3 has the same as EXT0
vincent.

Am 11.02.2015 um 22:58 schrieb internet-conception <notifications@github.com>:

**Comment by internet-conception** [comment]
Thank you Vincent to check my file ;)

I just re-upload the correct version of repetier with this clean setting :

#define EXT0_X_OFFSET 0
#define EXT0_Y_OFFSET 0

#define EXT1_X_OFFSET 1600
#define EXT1_Y_OFFSET 0

#define EXT2_X_OFFSET 1600
#define EXT2_Y_OFFSET 1600

#define EXT3_X_OFFSET 0
#define EXT3_Y_OFFSET 1600

But it's the same...

**Comment by vinmicgra** [comment]
What happens if you set

	� #define min_software_endstop_x false
	� #define max_software_endstop_x false
	� #define ALWAYS_CHECK_ENDSTOPS 1
?

**Comment by internet-conception** [comment]
nothings, same behaviour on homing x
Thank's again ;)

**Comment by vinmicgra** [comment]
Sorry, i mean:

#define ALWAYS_CHECK_ENDSTOPS 0

Same behaviour?

**Comment by internet-conception** [comment]
Oh yes, you are a genius...

It change ! 
https://www.youtube.com/watch?v=cKVw8Qmswx4

I'm a bit surprise lol I guess it work ...
I can digg a bit more to customize it perfectly but it work properly right ?

**Comment by vinmicgra** [comment]
It seems to work.

But you have a problem with your endstops, recheck the wiring and the correct usage of your endstop modules.
Maybe theres some crosstalk or wrong voltage levels. (3.3V?)

**Comment by internet-conception** [comment]
Ok I will continue to investigate.

But I have many things to try ! it's great, you really un-block me !!!
The "re-test" function is now working, and the fine tunning seems easy to do now ;)

A very big thank you Vincent !
Sincerly yours

**Comment by repetier** [comment]
All I saw is that 

#define min_software_endstop_x true
#define min_software_endstop_y true
#define min_software_endstop_z true
#define max_software_endstop_x true
#define max_software_endstop_y true
#define max_software_endstop_z true

is wrong. Software endstop is only allowed where hardware endstop is not present.

Except that from what I read it may in deed be crosstalk stopping the back move directly instead of when endstop is reached. Drill your endstop wires and motor wires, that is often enough to prevent it.

**Comment by internet-conception** [comment]
Thank's a lot Repetier, 
it's good to know the endstop software trick. I setup it properly and I finally understand how the X,Y offset work with multiple extruders :o) And it's great ! 
I just discovered yesterday that when you change the extruder dropdown selection in repetier host, it move alone to his new location, automagicaly !

So it took me a bit of time but I'm sure to know everything about it's configuration. And I should confess I was suspecting your firmware to be buged, I'm sorry ! your firmware is perfect ! the bug was betwen the chair and the keybord lol

And I would never achieve this "un-usual setup" without the help of VINCENT !!! Thank's a lot to you !
