### ISSUE TITLE
4 extruders extruder-cooler not working

### ISSUE THREAD

**Issue by Highcooley** [repetier/Repetier-Firmware#348]
With 4 extruders configured, the cooler fan function stops working properly (previous I had 2 extruders working fine).

Depending on the temperatures of the different extruders, the cooler sometimes switches on, when the heater of a certain extruder or a combination of extruders are turned on (mainly if the over all temperature of all extruders is close or above the min cooling temp). 

If at least one heater is turned on or t least one temperature is above min cooling temp, the PWM out LED slightly flickers.

**Comment by repetier** [comment]
The reason is that it was simply not supported. I have just updated work092 with a patch that hopefully works. Have no testing hardware here, so please let me know if it now works.

**Comment by Highcooley** [comment]
Thanks a lot for your reply! I'm gona try it out as soon as I fond the time.

**Comment by Highcooley** [comment]
All right, I gave it a shot. Unfortunately, it doesn't seem to work as it should. Now extruder 1 is fine, but the cooling doesn't react on all the other three extruders at all anymore.

However, this said. I just manually applied all your changes to my working 0.91 release. I found all the appropriate lines to alter, but of course don't know if there is any other change missing which would be implemented in 0.92. Maybe someone more into testing with a properly configured 0.92 with a multiextruder setup should give it a shot as well.

**Comment by repetier** [comment]
Ok, just to be sure. Important were changes in HAL.cpp, repetier.h and Extruder.cpp

To get working correctly you need to set the COOLER_PIN for all extruders to the same value. This is the only case where it is supposed to work.

You can add in manageTemperatures in extruder.cpp after

#if !SHARED_COOLER && NUM_EXTRUDER >= 2 && EXT0_EXTRUDER_COOLER_PIN == EXT1_EXTRUDER_COOLER_PIN && EXT0_EXTRUDER_COOLER_PIN >= 0

a
#error Compiling for shared

then you should see the compilation abort with that message and you are sure it wanted to enable shared cooler.

Ok writing this I see the error. The line should read

#if SHARED_COOLER && NUM_EXTRUDER >= 2 && EXT0_EXTRUDER_COOLER_PIN == EXT1_EXTRUDER_COOLER_PIN && EXT0_EXTRUDER_COOLER_PIN >= 0

without the ! before SHARED_COOLER

**Comment by Highcooley** [comment]
Thumbs up, it's working like a treat! Once again thank you very much for your super fast response and solution. Once again, Repetier Firmware has evolved one more step :-) Have a nice week!
