### ISSUE TITLE
GCODE_BUFFER_SIZE is redefined 

### ISSUE THREAD

**Issue by scp38** [repetier/Repetier-Firmware#354]
with commit e8b6f07278:

GCODE_BUFFER_SIZE is redefined in "Repetier.h"

    #include "Configuration.h"
    #define GCODE_BUFFER_SIZE 1 

original definition in "Configuration.h"

    #define GCODE_BUFFER_SIZE 2

**Comment by repetier** [comment]
Yes, I want to remove it from config. Next release will have it removed in Configuration.h. Thanks for the reminder.
