### ISSUE TITLE
Missing Stepper Motor Selection in Online Firmware Configuration

### ISSUE THREAD

**Issue by adamarumjahn** [repetier/Repetier-Firmware#358]
If you need to change your stepper motor to another one you may find that it is not shown.  

Recently I had to change my stepper designation for the Y motor to Extruder 2.  When I built my 2nd machine, I wanted to change this back.  I uploaded the old firmware (Y motor -> Extruder 2) and tried to change it back to Y motor -> Y motor in the online configuration tool but it seems to be missing and I can't select it.  It just keeps showing Extruder 2.  

I've attached a screen shot where I tried selecting Extruder 5, saving, reuploading the configuration.h file and running the tool again.  Same issue again.

![screen shot 2015-02-04 at 10 12 44 am](https://cloud.githubusercontent.com/assets/7477099/6042953/fb8bfba2-ac56-11e4-9ed5-f5182289a220.png)

**Comment by repetier** [comment]
Ok, that was a hard but important one. I have fixed it now. After a reload it should now work as expected.
