### ISSUE TITLE
Firmware configuration tool bug - changing the wrong stepper motor assignment

### ISSUE THREAD

**Issue by innovo3d** [repetier/Repetier-Firmware#366]
I'm having troubles with my stepper motors (missed steps, which may be an issue with my RUMBA board rather than the drivers FYI in case anyone else is having the same issue) so I decided to change the stepper driver socket from Y motor to Extruder 2.

When I uploaded the firmware and started up the machine I found out that it instead changed X to E2 and not Y to E2.  See pics below:

What I had configured in the online configurator:
![screen shot 2015-02-18 at 8 50 25 pm](https://cloud.githubusercontent.com/assets/7477099/6260714/e052f7d6-b7b0-11e4-8ed5-54d0de7a1852.png)

What was done in the configuration.h file:
![screen shot 2015-02-18 at 8 50 38 pm](https://cloud.githubusercontent.com/assets/7477099/6260716/e970b2b8-b7b0-11e4-8f69-288a06330817.png)

**Comment by repetier** [comment]
Fixed fo r0.92
