### ISSUE TITLE
EEPROM position for EPR_AUTORETRACT_ENABLED  is wrong, G11 stop print

### ISSUE THREAD

**Issue by luc-github** [repetier/Repetier-Firmware#378]
Currently in eeprom.h there are :
```#define EPR_RETRACTION_UNDO_SPEED 1016```
```#define EPR_AUTORETRACT_ENABLED 1018```
but **RETRACTION_UNDO_SPEED** is a float so we should have +4 for next position like
```#define EPR_AUTORETRACT_ENABLED 1020```

Because of this shift **RETRACTION_UNDO_SPEED** is set to 0 instead of 20 after a M502/M500, so if using G11 it will stop the print.

As mentioned earlier need to correct **EPR_AUTORETRACT_ENABLED**  to
```#define EPR_AUTORETRACT_ENABLED 1020 ```in eeprom.h to avoid the overwrite

And if I can suggest : it would be good to not allow speed equal to 0 by adding some check and error message when processing, because not easy to find.

**Comment by repetier** [comment]
You are right with the positions.

I can not directly prevent wrong speeds, but now it gets used as max(1 , speed) so values < 1 have no effect.
