### ISSUE TITLE
BUG: Fan not working on RAMPS 1.3

### ISSUE THREAD

**Issue by VladimirP1** [repetier/Repetier-Firmware#379]
**#define ORIG_FAN_PIN            9**
#define ORIG_PS_ON_PIN          12

#define HEATER_0_PIN       10
#define HEATER_1_PIN       8
**#define HEATER_2_PIN       9**

**It is in pins.h.
Second heater and fan on the same pin.**

**Comment by repetier** [comment]
Yes, RAMPS has no dedicated fan output. So if you have 1 extruder you use the second output as fan. If you have 2 extruder + bed you need to disable fan feature or add an extension board and set FAN_PIN to the number there.
