### ISSUE TITLE
Bluetooth Serial bug

### ISSUE THREAD

**Issue by errolt** [repetier/Repetier-Firmware#380]
Hi Repetier et al,

When compiling with bluetooth serial port enabled, with Adruino 1.6.1 it kicks out the following error:
HAL.cpp:1164:26: error: attempt to use poisoned "SIG_USART2_RECV"

Thank you,
Errol

**Comment by repetier** [comment]
SIG_USART2_RECV is in newer gcc version
USART2_RECV_vect

Have now renamed it in the hope to get no complains form users with old arduino IDEs not having that variable.
