### ISSUE TITLE
Speed multiplier adjusted instead of flowrate in 0.92 work extruder.cpp

### ISSUE THREAD

**Issue by hannoHI** [repetier/Repetier-Firmware#386]
line 560 of Extruder.cpp should ajustt flow rate and not speed.
should  use Commands::changeFlowrateMultiply(Printer::extrudeMultiply); // needed to adjust extrusionFactor to possibly different diameter 
instead of 
Commands::changeFeedrateMultiply(Printer::extrudeMultiply); // needed to adjust extrusionFactor to possibly different diameter

**Comment by repetier** [comment]
Yes, that is correct. Thanks for the hint. Will be fixed in the next update.
