### ISSUE TITLE
PID autotune broken for heated bed

### ISSUE THREAD

**Issue by makertum** [repetier/Repetier-Firmware#415]
My setup is a Rumba Board with Repetier 0.92.3, with 1 nozzle heater, 3 extruders and 1 heated bed installed. Heating up the bed using M140 or M190 works fine. PID also works fine on bed and extruders.

But the PID autotune for the heated bed seems to be broken, I tried

M303 P C8 S110
M303 P-1 C8 S110
M303 E-1 C8 S110

All of these cause Repetier to start the PID autotune for the installed nozzle heater, not the bed. Probably a typo somewhere in the code.

**Comment by axjurado** [comment]
i had the same issue, had to use P3 in order to work

**Comment by repetier** [comment]
P sets heater. 0-2 are extruder 02 and P3 is then the bed.
