### ISSUE TITLE
LCD support hangs ATmega

### ISSUE THREAD

**Issue by ghost** [repetier/Repetier-Firmware#42]
Full details here: http://forums.reprap.org/read.php?146,160309,160323#msg-160323

If I set #define UI_DISPLAY_TYPE to 0 or 4 - and upload, I can connect from host software

If I set #define UI_DISPLAY_TYPE to 2 or 3 - It seems to hang the AVR and I can not connect

Peter

**Comment by boelle** [comment]
i wonder if @ghost still have an issue here?

if no one has the issue it could be closed and short up the list
