### ISSUE TITLE
0.92.4 - Z_PROBE_BED_DISTANCE wrongly adds to total z-height

### ISSUE THREAD

**Issue by HarrySiegel** [repetier/Repetier-Firmware#426]
I'm using a CoreXY, and it seems that for all G29/G31/G32 commands Z_PROBE_BED_DISTANCE is added to the total z-height before printing. Not sure if or why that was intended or not, but it seems wrong to me.

The probe itself works well and A G29/G31/G32 leaves the nozzle exactly at 6.1mm above the print bed as expected from my configuration. But the average z-error reported always adds Z_PROBE_BED_DISTANCE to the real z-value (so 6.1mm + 5mm). So while in reality the probe travels 5mm, the error reported is 11.1mm. Needless to say, that a G32 before the print starts leads to a nozzle crash.

I'm using FW 0.92.4 and this is my z-probe-config: 

#define Z_PROBE_Z_OFFSET 0
#define Z_PROBE_Z_OFFSET_MODE 1
#define UI_BED_COATING 1
#define FEATURE_Z_PROBE 1
#define Z_PROBE_BED_DISTANCE 5
#define Z_PROBE_PIN ORIG_Z_MIN_PIN
#define Z_PROBE_PULLUP 1
#define Z_PROBE_ON_HIGH 1
#define Z_PROBE_X_OFFSET -25
#define Z_PROBE_Y_OFFSET -10
#define Z_PROBE_WAIT_BEFORE_TEST 0
#define Z_PROBE_SPEED 2
#define Z_PROBE_XY_SPEED 150
#define Z_PROBE_SWITCHING_DISTANCE 1.5 
#define Z_PROBE_REPETITIONS 5
#define Z_PROBE_HEIGHT 1.1

**Comment by repetier** [comment]
Yes it does because of this:

#if Z_PROBE_Z_OFFSET_MODE == 1
    distance += EEPROM::zProbeBedDistance();
#endif

In other words you said you have a inductive sensor measuring distance to real bed and your bed coating is 5mm. Since inductive sensors do not measure the coating we have to add it. So you can either set Z_PROBE_Z_OFFSET_MODE 0 or set your bed coating to 0 or both.
