### ISSUE TITLE
Thermo Coupled Fan breaks bed temperature readings

### ISSUE THREAD

**Issue by nmaggioni** [repetier/Repetier-Firmware#461]
If I enable the thermo coupled fan, assigning it to the same heater port I've used for fan control until now and linking its temperature to the hot end's thermistor, the heated bed's thermistor starts reading the same temperature as the hot end.
Disabling the thermo coupled fan and reverting back to manually controlling its speed solves this weird behavior.

I'm running a *RAMPS v1.4* and I've setup the firmware using the online configuration tool as of **23/01/2015**.

[Configuration.h](https://github.com/repetier/Repetier-Firmware/files/101945/Configuration.txt)

**Comment by repetier** [comment]
The problem should be fixed by now. Bed temp reading was reading the wrong index in that special case.

**Comment by nmaggioni** [comment]
Thanks!
