### ISSUE TITLE
Massive retraction during warmup - unit confusion

### ISSUE THREAD

**Issue by JBKingdon** [repetier/Repetier-Firmware#462]
Hi,

After using the online configuration tool and uploading the new firmware (with a new eeprom set), during warmup my 5mm wait retract turned into a 900mm one, which took quite a while! It seems the config tool puts the requested retract distance times the steps/mm setting into the config, where as the firmware is expecting a value in mm. Editing the eeprom value with r-host is a work around.

Regards,

**Comment by repetier** [comment]
Are you using latest 0.92.8 version? I remember having changed it sometime, but checking the code it nowhere has a conversion. It's always mm.

**Comment by JBKingdon** [comment]
Yes, sorry, I should have given that. 0.92.8 downloaded using the config tool on Jan 21 2016.

The issue I think must be in the config tool, as the large value is in the downloaded configuration.h:

#define EXT0_WAIT_RETRACT_UNITS 925

Regards,

**Comment by repetier** [comment]
Ok, that helped. It was the config tool still doing the multiply while firmware was already fixed to accept mm instead of steps. Should now be fixed for next download.

**Comment by JBKingdon** [comment]
Great work - many thanks.
