### ISSUE TITLE
Autoleveling doesn't work - Z-probe:NAN

### ISSUE THREAD

**Issue by mikozak** [repetier/Repetier-Firmware#472]
**My configuration:**
- Kossel Mini
- RAMPS 1.4 with Arduino Mega
- Repetier 0.92.8

**Issue**
Recently I've installed z-probe using simple switch.
Configured autoleveling using web interface (3 points autoleveling)
When I issue G32 it doesn't work, procedure stops and printer reports an error. Here are the logs copied from repetier host (note line with Z-probe:NaN):

> 20:07:02.838 : Printer reset detected - initalizing
> 20:07:02.841 : start
> 20:07:02.842 : Info:External Reset
> 20:07:02.851 : Transformation matrix: 1.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000 1.000000
> 20:07:05.509 : Free RAM:984
> 20:07:05.509 : Autoretract:0
> 20:07:05.513 : X:0.00 Y:0.00 Z:0.000 E:0.0000
> 20:07:05.513 : SelectExtruder:0
> 20:07:05.537 : FIRMWARE_NAME:Repetier_0.92.8 FIRMWARE_URL:https://github.com/repetier/Repetier-Firmware/ PROTOCOL_VERSION:1.0 MACHINE_TYPE:Delta EXTRUDER_COUNT:1 REPETIER_PROTOCOL:3
> 20:07:05.538 : Printed filament:0.00m Printing time:0 days 0 hours 0 min
> 20:07:05.538 : PrinterMode:FFF
> 20:07:05.556 : X:0.00 Y:0.00 Z:0.000 E:0.0000
> 20:07:05.556 : DebugLevel:6
> 20:07:05.556 : SelectExtruder:0
> 20:07:05.556 : Begin file list
> 20:07:05.559 : End file list
> 20:07:05.560 : DebugLevel:6
> 20:07:05.562 : SelectExtruder:0
> 20:07:24.576 : EPR:0 1028 0 Language
> 20:07:24.578 : EPR:2 75 115200 Baudrate
> 20:07:24.598 : EPR:3 129 0.000 Filament printed [m]
> 20:07:24.601 : EPR:2 125 0 Printer active [s]
> 20:07:24.610 : EPR:2 79 0 Max. inactive time [ms,0=off]
> 20:07:24.612 : EPR:2 83 360000 Stop stepper after inactivity [ms,0=off]
> 20:07:24.614 : EPR:3 11 99.5000 Steps per mm
> 20:07:24.617 : EPR:3 23 150.000 Max. feedrate [mm/s]
> 20:07:24.619 : EPR:3 35 90.000 Homing feedrate [mm/s]
> 20:07:24.621 : EPR:3 39 10.000 Max. jerk [mm/s]
> 20:07:24.623 : EPR:3 133 0.000 X min pos [mm]
> 20:07:24.625 : EPR:3 137 0.000 Y min pos [mm]
> 20:07:24.627 : EPR:3 141 0.000 Z min pos [mm]
> 20:07:24.629 : EPR:3 145 200.000 X max length [mm]
> 20:07:24.632 : EPR:3 149 200.000 Y max length [mm]
> 20:07:24.634 : EPR:3 153 219.443 Z max length [mm]
> 20:07:24.636 : EPR:3 59 1000.000 Acceleration [mm/s^2]
> 20:07:24.638 : EPR:3 71 100.000 Travel acceleration [mm/s^2]
> 20:07:24.641 : EPR:3 881 212.300 Diagonal rod length [mm]
> 20:07:24.644 : EPR:3 885 105.280 Horizontal rod radius at 0,0 [mm]
> 20:07:24.646 : EPR:3 925 75.000 Max printable radius [mm]
> 20:07:24.649 : EPR:1 891 70 Segments/s for travel
> 20:07:24.651 : EPR:1 889 180 Segments/s for printing
> 20:07:24.655 : EPR:1 893 29 Tower X endstop offset [steps]
> 20:07:24.657 : EPR:1 895 0 Tower Y endstop offset [steps]
> 20:07:24.660 : EPR:1 897 69 Tower Z endstop offset [steps]
> 20:07:24.662 : EPR:3 901 210.000 Alpha A(210):
> 20:07:24.665 : EPR:3 905 330.000 Alpha B(330):
> 20:07:24.667 : EPR:3 909 90.000 Alpha C(90):
> 20:07:24.670 : EPR:3 913 0.000 Delta Radius A(0):
> 20:07:24.672 : EPR:3 917 0.000 Delta Radius B(0):
> 20:07:24.675 : EPR:3 921 0.000 Delta Radius C(0):
> 20:07:24.677 : EPR:3 933 0.757 Corr. diagonal A [mm]
> 20:07:24.679 : EPR:3 937 0.581 Corr. diagonal B [mm]
> 20:07:24.682 : EPR:3 941 0.000 Corr. diagonal C [mm]
> 20:07:24.684 : EPR:3 1024 0.000 Coating thickness [mm]
> 20:07:24.687 : EPR:3 808 5.910 Z-probe height [mm]
> 20:07:24.696 : EPR:3 929 2.000 Max. z-probe - bed dist. [mm]
> 20:07:24.699 : EPR:3 812 2.000 Z-probe speed [mm/s]
> 20:07:24.702 : EPR:3 840 50.000 Z-probe x-y-speed [mm/s]
> 20:07:24.705 : EPR:3 800 30.200 Z-probe offset x [mm]
> 20:07:24.707 : EPR:3 804 -6.670 Z-probe offset y [mm]
> 20:07:24.709 : EPR:3 816 30.000 Z-probe X1 [mm]
> 20:07:24.712 : EPR:3 820 0.000 Z-probe Y1 [mm]
> 20:07:24.715 : EPR:3 824 -30.000 Z-probe X2 [mm]
> 20:07:24.718 : EPR:3 828 0.000 Z-probe Y2 [mm]
> 20:07:24.720 : EPR:3 832 -30.000 Z-probe X3 [mm]
> 20:07:24.723 : EPR:3 836 0.000 Z-probe Y3 [mm]
> 20:07:24.727 : EPR:3 1036 0.000 Z-probe bending correction A [mm]
> 20:07:24.731 : EPR:3 1040 0.000 Z-probe bending correction B [mm]
> 20:07:24.736 : EPR:3 1044 0.000 Z-probe bending correction C [mm]
> 20:07:24.739 : EPR:0 880 0 Autolevel active (1/0)
> 20:07:24.744 : EPR:0 1020 0 Enable retraction conversion [0/1]
> 20:07:24.746 : EPR:3 992 5.000 Retraction length [mm]
> 20:07:24.749 : EPR:3 1000 80.000 Retraction speed [mm/s]
> 20:07:24.752 : EPR:3 1004 0.200 Retraction z-lift [mm]
> 20:07:24.756 : EPR:3 1008 0.100 Extra extrusion on undo retract [mm]
> 20:07:24.761 : EPR:3 1016 80.000 Retraction undo speed
> 20:07:24.765 : EPR:3 200 156.000 Extr.1 steps per mm
> 20:07:24.769 : EPR:3 204 50.000 Extr.1 max. feedrate [mm/s]
> 20:07:24.773 : EPR:3 208 20.000 Extr.1 start feedrate [mm/s]
> 20:07:24.777 : EPR:3 212 5000.000 Extr.1 acceleration [mm/s^2]
> 20:07:24.781 : EPR:0 216 3 Extr.1 heat manager [0-3]
> 20:07:24.785 : EPR:0 217 230 Extr.1 PID drive max
> 20:07:24.788 : EPR:0 245 40 Extr.1 PID drive min
> 20:07:24.791 : EPR:3 218 7.0000 Extr.1 PID P-gain/dead-time
> 20:07:24.794 : EPR:3 222 2.0000 Extr.1 PID I-gain
> 20:07:24.804 : EPR:3 226 40.0000 Extr.1 PID D-gain
> 20:07:24.807 : EPR:0 230 255 Extr.1 PID max value [0-255]
> 20:07:24.809 : EPR:2 231 0 Extr.1 X-offset [steps]
> 20:07:24.812 : EPR:2 235 0 Extr.1 Y-offset [steps]
> 20:07:24.814 : EPR:2 290 0 Extr.1 Z-offset [steps]
> 20:07:24.817 : EPR:1 239 1 Extr.1 temp. stabilize time [s]
> 20:07:24.819 : EPR:1 250 150 Extr.1 temp. for retraction when heating [C]
> 20:07:24.822 : EPR:1 252 0 Extr.1 distance to retract when heating [mm]
> 20:07:24.825 : EPR:0 254 255 Extr.1 extruder cooler speed [0-255]
> 20:07:52.745 : Info:Autoleveling enabled
> 20:07:52.753 : Transformation matrix: 1.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000 1.000000
> 20:07:52.756 : SelectExtruder:0
> 20:08:04.386 : Info:Autoleveling disabled
> 20:08:09.211 : SelectExtruder:0
> 20:08:09.219 : X:0.00 Y:0.00 Z:219.447 E:0.0000
> 20:08:15.938 : Z-probe:NAN X:30.01 Y:-0.01
> 20:08:20.292 : Z-probe:NAN X:-29.99 Y:-0.01
> 20:08:22.189 : Z-probe:NAN X:-29.99 Y:-0.01
> 20:08:23.115 : plane: a = NAN b = NAN c = NAN
> 20:08:23.123 : Transformation matrix: NAN NAN NAN 0.000000 NAN NAN NAN NAN NAN
> 20:08:23.123 : CurrentZ:NAN atZ:7.91
> 20:08:23.127 : Z after rotation:NAN
> 20:08:23.127 : Printer height:NAN
> 20:08:23.128 : Error:A hit floor
> 20:08:23.131 : Error:A hit floor
> 20:08:23.135 : Warning:Invalid delta coordinate - move ignored x:-5917 y:647 z:-2147483648
> 20:08:23.143 : Warning:in queueDeltaMove to calculateDeltaSubSegments returns error.
> 20:08:23.147 : Warning:moveRelativeDistanceInSteps / queueDeltaMove returns error
> 20:08:23.151 : Info:Autoleveling enabled
> 20:08:23.151 : Error:G32
> 20:08:23.155 : X:NAN Y:NAN Z:NAN E:0.0000
> 20:08:23.155 : Info:Autoleveling disabled
> 20:08:23.269 : RequestPause:Homing failed!
> 20:08:23.269 : Error:A hit floor
> 20:08:23.270 : Error:A hit floor
> 20:08:23.270 : Warning:Invalid delta coordinate - move ignored x:0 y:0 z:2147483579
> 20:08:23.270 : Warning:in queueDeltaMove to calculateDeltaSubSegments returns error.
> 20:08:23.271 : Warning:moveRelativeDistanceInSteps / queueDeltaMove returns error
> 20:08:23.271 : Error:A hit floor
> 20:08:23.272 : SelectExtruder:0
> 20:08:23.274 : X:0.00 Y:0.00 Z:-21582750.000 E:0.0000
> 20:08:23.274 : Info:Autoleveling enabled
> 20:08:32.574 : Error:isPositionAllowed
> 20:08:32.574 : X:NAN Y:NAN Z:NAN E:0.0000
> 20:08:32.578 : Error:isPositionAllowed
> 20:08:32.582 : X:NAN Y:NAN Z:NAN E:0.0000
> 20:08:32.582 : Error:isPositionAllowed
> 20:08:32.586 : X:NAN Y:NAN Z:NAN E:0.0000
> 20:09:02.330 : Warning: Seems like we missed a ok, got a wait - continue sending.
> 20:16:40.426 : Printer reset detected - initalizing
> 20:16:40.426 : start
> 20:16:40.430 : Info:External Reset
> 20:16:40.434 : Info:Autoleveling enabled
> 20:16:40.443 : Transformation matrix: 1.000000 0.000000 0.000000 0.000000 1.000000 0.000000 0.000000 0.000000 1.000000
> 20:16:43.101 : Free RAM:984
> 20:16:43.101 : Autoretract:0
> 20:16:43.105 : X:0.00 Y:0.00 Z:0.000 E:0.0000
> 20:16:43.105 : SelectExtruder:0
> 20:16:43.122 : FIRMWARE_NAME:Repetier_0.92.8 FIRMWARE_URL:https://github.com/repetier/Repetier-Firmware/ PROTOCOL_VERSION:1.0 MACHINE_TYPE:Delta EXTRUDER_COUNT:1 REPETIER_PROTOCOL:3
> 20:16:43.125 : Printed filament:0.00m Printing time:0 days 0 hours 0 min
> 20:16:43.130 : PrinterMode:FFF
> 20:16:43.134 : X:0.00 Y:0.00 Z:0.000 E:0.0000
> 20:16:43.134 : DebugLevel:6
> 20:16:43.144 : SelectExtruder:0
> 20:16:43.144 : Begin file list
> 20:16:43.144 : End file list
> 20:16:43.146 : Info:Autoleveling disabled
> 20:16:47.971 : SelectExtruder:0
> 20:16:47.975 : X:0.00 Y:0.00 Z:219.447 E:0.0000
> 20:16:54.751 : Z-probe:NAN X:30.01 Y:-0.01
> 20:16:59.056 : Z-probe:NAN X:-29.99 Y:-0.01
> 20:17:00.904 : Z-probe:NAN X:-29.99 Y:-0.01
> 20:17:01.830 : plane: a = NAN b = NAN c = NAN
> 20:17:01.834 : Transformation matrix: NAN NAN NAN 0.000000 NAN NAN NAN NAN NAN
> 20:17:01.834 : CurrentZ:NAN atZ:7.91
> 20:17:01.838 : Z after rotation:NAN
> 20:17:01.838 : Printer height:NAN
> 20:17:01.842 : Error:A hit floor
> 20:17:01.842 : Error:A hit floor
> 20:17:01.850 : Warning:Invalid delta coordinate - move ignored x:-5917 y:647 z:-2147483648
> 20:17:01.854 : Warning:in queueDeltaMove to calculateDeltaSubSegments returns error.
> 20:17:01.863 : Warning:moveRelativeDistanceInSteps / queueDeltaMove returns error
> 20:17:01.863 : Info:Autoleveling enabled
> 20:17:01.863 : Error:G32
> 20:17:01.867 : X:NAN Y:NAN Z:NAN E:0.0000
> 20:17:01.870 : Info:Autoleveling disabled
> 20:17:01.961 : RequestPause:Homing failed!
> 20:17:01.962 : Error:A hit floor
> 20:17:01.964 : Error:A hit floor
> 20:17:01.971 : Warning:Invalid delta coordinate - move ignored x:0 y:0 z:2147483579
> 20:17:01.971 : Warning:in queueDeltaMove to calculateDeltaSubSegments returns error.
> 20:17:01.978 : Warning:moveRelativeDistanceInSteps / queueDeltaMove returns error
> 20:17:01.978 : Error:A hit floor
> 20:17:01.981 : SelectExtruder:0
> 20:17:01.985 : X:0.00 Y:0.00 Z:-21582750.000 E:0.0000
> 20:17:01.985 : Info:Autoleveling enabled
> 20:17:01.994 : DebugLevel:6
> 20:17:01.994 : SelectExtruder:0
> 20:18:08.343 : Error:isPositionAllowed
> 20:18:08.343 : X:NAN Y:NAN Z:NAN E:0.0000
> 20:18:08.347 : Error:isPositionAllowed
> 20:18:08.348 : X:NAN Y:NAN Z:NAN E:0.0000
> 20:18:08.351 : Error:isPositionAllowed
> 20:18:08.355 : X:NAN Y:NAN Z:NAN E:0.0000

**Comment by mikozak** [comment]
For the example I decribed here I used 3 points probing.
Now I just reconfigured it to use grid 2x2 and it works without issues.

**Comment by repetier** [comment]
Strange. The part that fails is z probing and that is the same for 3 point and 4 point measurement. It is also the same for G30 just as a test.  To fail with NaN one of the used values must be NaN, normally a eeprom variable, but they seem all correct. So I assume the difference you did betwenn made the problem vanish.

**Comment by mikozak** [comment]
I discovered in code that function that corrects calculated z-probe distance by bending returns NaN

**Comment by repetier** [comment]
I see. Your 3 points are on a line and that is not allowed. That creates a division by zero causing the NaN. For 3 point measurement these must be as wide aparat as possible in different corners. For 4 point also but I guess yo changed them to build the 2 axis fixing that.
