### ISSUE TITLE
Use of Flowrate function in Repetier-Host causes printer to become extremely slow and jittery

### ISSUE THREAD

**Issue by connerk** [repetier/Repetier-Firmware#48]
each time I attempt to change Flowrate the printer begins to print extremely slow and jittery. returning 
returning Flowrate to 100% and pausing the printer for around 10 seconds resolves the slow jitter. Pausing momentarily when Flowrate is <>100% rectifies the jitter momentarily, but it returns quickly.

Arduino 2564
RAMPS 1.4 w/ SD
Repetier Firmware 0.73
EEPROM Settings enabled
12v ATX
Pololu 4988
Windows 8

**Comment by boelle** [comment]
@connerk are you still having the issue after all these years? or can we close the issue and call it solved?

i think that @repetier would love to have the issue list as short as possible

**Comment by repetier** [comment]
I think it is solved. Will close all open issues once V2 start to be usable so I can concentrate on the active bugs.

**Comment by boelle** [comment]
will it be usefull if i read all open issues and make a comment on them? i have notthing better to do anyway

**Comment by repetier** [comment]
That would spam me with messages only. I think easiest is if I just close them once I'm at that point. Should be done in an hour if I just paste same hint and close.

**Comment by boelle** [comment]
yep, not as smart as i thought. 

and i guess it will take some time to close them too as (if it was me) you would have to give every issue a fast read to see if looks solved or if it is an feature request or idea you could use for V2
