### ISSUE TITLE
Autoleveling corexy problem

### ISSUE THREAD

**Issue by maglo18** [repetier/Repetier-Firmware#504]
When i switch on auto leveling option in firmware an move my bed in z axis motors in x and y axis move a little bit on the left and right (few steps). Finally my printing model have diagonal stripes. When autoloveling is off i don't have this issues.

**Comment by repetier** [comment]
If your bed is not planar it must move xy when you go up with z. Just think a bed with 10° rotation and you see what I mean. That is what autoleveling does. You can reduce this if you level the bed better by hand, then it has less to correct and you get less artifacts from level adjustment.
