### ISSUE TITLE
current git not compiling when FEATURE_AUTOLEVEL or FEATURE_Z_PROBE are not set

### ISSUE THREAD

**Issue by Links2004** [repetier/Repetier-Firmware#507]
the PlaneBuilder  class is missing when 
```FEATURE_AUTOLEVEL``` or ```FEATURE_Z_PROBE``` are not enabled
this end up in compiling error:

```
../BedLeveling.cpp: In static member function 'static float Printer::bendingCorrectionAt(float, float)':
../BedLeveling.cpp:541:2: error: 'PlaneBuilder' was not declared in this scope
  PlaneBuilder builder;
  ^
../BedLeveling.cpp:541:15: error: expected ';' before 'builder'
  PlaneBuilder builder;
               ^
../BedLeveling.cpp:542:5: error: 'builder' was not declared in this scope
     builder.addPoint(EEPROM::zProbeX1(),EEPROM::zProbeY1(),EEPROM::bendingCorrectionA());
     ^
make: *** [BedLeveling.cpp.o] Error 1
```

see:
https://github.com/repetier/Repetier-Firmware/blob/6e817068efe34d30b0f2769378f6d108b723a981/src/ArduinoAVR/Repetier/BedLeveling.cpp#L113
https://github.com/repetier/Repetier-Firmware/blob/6e817068efe34d30b0f2769378f6d108b723a981/src/ArduinoAVR/Repetier/BedLeveling.cpp#L541

**Comment by repetier** [comment]
Thanks is now fixed in latest master version.
