### ISSUE TITLE
question about the ADC in the firmware code

### ISSUE THREAD

**Issue by JasonShed** [repetier/Repetier-Firmware#514]
In the firmware code,I'm confused about that： 
currentTemperature = (1023<<(2-ANALOG_REDUCE_BITS))-(osAnalogInputValues[sensorPin]>>(ANALOG_REDUCE_BITS))
what does the "ANALOG_REDUCE_BITS" mean? can you explain this code?

another is about the sensorType,in "void TemperatureController::updateCurrentTemperature()",
the sensorType are all numbers,I don't know which one is which one.Is there having materials about that?

**Comment by repetier** [comment]
We use internally 12bit resolution for analog inputs, ANALOG_REDUCE_BITS corrects the oversampled result to exactly 12bit, so it is the same for all hardware platforms.

The sensor types are described in the configuration.h file on github for extruder 0 where you set it.
