### ISSUE TITLE
comment of uint8_t PrintLine::queueNonlinearMove()

### ISSUE THREAD

**Issue by voicevon** [repetier/Repetier-Firmware#519]
Location: motion.cpp
uint8_t PrintLine::queueNonlinearMove()

Comment of the third param 
@param delta_step_rate delta step rate in segments per second for the move.
It doesn't match "uint8_t softEndstop"

**Comment by repetier** [comment]
Sorry, but what do you want to say here? third param is softEndstop but what is the problem?

**Comment by voicevon** [comment]
Sorry, I didn't clearly express myself
The following  is the description of the third param in comment 
        @param _**delta_step_rate delta step rate in segments per second for the move.**_
Now , let's take a look of function definition:
uint8_t PrintLine::queueNonlinearMove(uint8_t check_endstops,uint8_t pathOptimize, **_uint8_t softEndstop_**)

They are  not the same name. I guess the comment description is wrong.
Thanks.

**Comment by repetier** [comment]
Ok, now I understand. Fixed for next release.
