### ISSUE TITLE
hi,DUAL Z  ENDSTOPS

### ISSUE THREAD

**Issue by linjinc** [repetier/Repetier-Firmware#528]
Z_DUAL_ENDSTOPS is a feature to enable the use of 2 endstops for both Z steppers - Let's call them Z stepper and Z2 stepper.
  That way the machine is capable to align the bed during home, since both Z steppers are homed.
 
  After Z homing, this adjustment is applied to just one of the steppers in order to align the bed.
  One just need to home the Z axis and measure the distance difference between both Z axis and apply the math: Z adjust = Z - Z2.
  If the Z stepper axis is closer to the bed, the measure Z > Z2 (yes, it is.. think about it) and the Z adjust would be positive.
  Play a little bit with small adjustments (0.5mm) and check the behaviour.

**Comment by repetier** [comment]
Nice explanation, but what is the issue? Have you implemented this feature? Would be great as I have no printer with such a setup.

**Comment by linjinc** [comment]
https://github.com/MarlinFirmware/Marlin
marlin is ok

I have a machine.
dual z endstop
![image](https://cloud.githubusercontent.com/assets/10563028/15450123/230c7254-1fc6-11e6-88be-10db7d101afc.png)

**Comment by repetier** [comment]
Ok, but what is your intention of the post?

**Comment by linjinc** [comment]
I want to use repetier firmware
But repetier firmware does not have  dual Z endstop

**Comment by repetier** [comment]
Ok, so you want me to implement this feature. In theory it is simple but having no printer for testing I never implemented it. If you are up to testing it until it works as expected I can write the modifications. Might be some tests required to get it going right. So say only yes if you will do it to the final end.

**Comment by linjinc** [comment]
thank you
ok,

**Comment by repetier** [comment]
Ok, here we go. Please use the latest development version for this. In config tool add in manual tab the following

#define MINMAX_HARDWARE_ENDSTOP_Z2 1
#define Z2_MINMAX_PIN 16
#define ENDSTOP_Z2_MINMAX_INVERTING 0
#define ENDSTOP_PULLUP_Z2_MINMAX 0

of course adjusted for your endstop type and pins. That should do the trick. M119 should show 2 z endstop values now. Test both and test homing. Hold a hand on power on first test if it does not stop, but I'm quite confident that I captured the right logic.

**Comment by linjinc** [comment]
thank
I am here is the early morning, tomorrow test

**Comment by linjinc** [comment]
Normal working
But I'll be testing a little more.

**Comment by linjinc** [comment]
Z1 Morot and Z2 motor is not parallel
Z1 Sometimes pause
Z2 no problem

**Comment by linjinc** [comment]
![image](https://cloud.githubusercontent.com/assets/10563028/15468468/fbe09ba4-2116-11e6-8700-7e12b1d710c0.png)
![image](https://cloud.githubusercontent.com/assets/10563028/15468478/07fcd7b8-2117-11e6-9884-426291257559.png)
![image](https://cloud.githubusercontent.com/assets/10563028/15468487/112fb1fc-2117-11e6-926f-34b945d341f6.png)

**Comment by repetier** [comment]
What do you mean with z1 sometimes pauses? During a single move it stops and goes? That could be from friction if they are not parallel. The only big question is if they are not parallel, if only one motor stops and the other moves a bit longer. If you tried that and have to much difference the friction can make motors stall.

You could try with slower homing speed for testing to see difference.

**Comment by linjinc** [comment]
Please forgive me for using Google Translation
May be set incorrectly, I will continue to test

**Comment by linjinc** [comment]
I'm starting to use it, everything is okay.
Thank

**Comment by Thump2010** [comment]
I had not used repetier before due to the lack of dual z endstop support. I did what is listed here, I have both motors moving in the right dir, I have both endstops able to trigger, I can see them trigger with M119 but when I home the Z axis it ignores the trigger and just keeps going so I have to power off.

**Comment by shaiss** [comment]
@linjinc can you share a bit more on how you set this up?  What board and where is your 2nd z motor plugged into?

**Comment by siggi60** [comment]
Hi and sorry for gravedigging,
ist it also easy to setup a third Z-Endstop? I don't really believe that all is done by adding some lines like them:

#define MINMAX_HARDWARE_ENDSTOP_Z3 1
#define Z3_MINMAX_PIN 16
#define ENDSTOP_Z3_MINMAX_INVERTING 0
#define ENDSTOP_PULLUP_Z3_MINMAX 0

My intention is it might be better to use three optical or hall endstops then one inductive sensor to do mabl.

Thanks for reading
