### ISSUE TITLE
configuration tool: download buttons

### ISSUE THREAD

**Issue by Spongman** [repetier/Repetier-Firmware#562]
is there any chance you can change the way the download buttons work on the last page of the configuration tool?

currently, when you press "Download Configuration.h" it replaces the page with the contents of Configuration.h. The problem is that if you want to (maybe repeatedly) tweak a configuration setting and download another configuration.h you have to start all over from the beginning uploading the configuration.h. this could be improved by either:
1) opening the download in a new window (`"_blank"`, instead of `"_self"`), in configurator.js or
2) adding a "`Content-Disposition: attachment; filename='Configuration.h'`" header in config.php - this will cause the browser to download the file, instead of showing it in a window.

**Comment by Kulitorum** [comment]
This does not happen to me, my computer just downloads the .h file as a file, and the webpage stays up.

I think you need to change some preferences in your browser - start by trying to use another browser, and go from there.

**Comment by Spongman** [comment]
looks like this was fixed on the server with the adding of a Content-Disposition header
