### ISSUE TITLE
All gcodes that Repetier-Firmware support

### ISSUE THREAD

**Issue by ghpenguin** [repetier/Repetier-Firmware#565]
I found it  in Repetier-Firmware-0.92.8/src/ArduinoAVR/Repetier/Repetier.ino  file.

Gcode list on the wiki page is out of date.

**Comment by quixand** [comment]
I added a link to the arduino file, but unsure what needs to happen to that Wiki page?

**Comment by repetier** [comment]
I guess your solution is the best for now.

Didn't know others can edit the wiki page as well.
