### ISSUE TITLE
Controller resets when doing G28

### ISSUE THREAD

**Issue by strips** [repetier/Repetier-Firmware#582]
I have been having some strangeness and now decided to test latest development. 

Did a git pull origin development and am now at ec3c389. Uploaded my latest dev Config to config tool and made some offset changes. Setting E0 as "0" and E1 and Z probe with their offsets relative to E0.

I also did a M502 and M500 but no other changes after this.

When I now connect to printer and do a G28 it finishes Y, X and resets just as it should start Z homing. Maybe I have something wrong in my Config but it should not reset?

[Configuration.h.txt](https://github.com/repetier/Repetier-Firmware/files/495166/Configuration.h.txt)

[octoprint_log.txt](https://github.com/repetier/Repetier-Firmware/files/495174/octoprint_log.txt)

**Comment by strips** [comment]
I'm curious about the E1 offsets. Shouldn't they be in mm?
#define EXT1_X_OFFSET 4775
#define EXT1_Y_OFFSET -6710

Just went through my config again. Looks like I entered , as decimal separator like I natively use :(

Building and will retry asap.

**Comment by strips** [comment]
Still get reset when doing G28 with:
#define EXT1_X_OFFSET 29.843
#define EXT1_Y_OFFSET -18.64

I had to manually change the values after the config tool wants them to be 4775 and -6710.

**Comment by repetier** [comment]
Offset is in steps. Config tool converts it from mm to steps. But that should not be the problem.
What is obvious is that the printer reboots/restarts. Log was missing the reason - normally you see if it was reset/brown out/... Homing z is just moving Z so first test would be moving z without homing. Initally z is at z=0 so moving up should be possible. If it also resets there you know z moves cause reset and you can continue from there. Might be a short causing voltage drop/reboot or just wrong pins for z driver. That is to determine.

**Comment by strips** [comment]
Ah, that explains the offset.

Of course I can not 100% rule out brownout but I'm 96% sure it is not as the printer could home fine before upgrading to latest dev from a relative new dev. And I'm able to move the Z axis all the way up and down by knob in display and GCODE/Octoprint.

So my bet is something in the Config combined with the dev branch. Unfortunately I did also some minor offset changes in fw. I could try to go back if I have the older one still.

**Comment by strips** [comment]
I flashed an development I compiled 23.09 and now I'm able to home all axis without any reset.

**Comment by repetier** [comment]
One thing that sometime happens is with high z steps per mm and high homing speed there is no time to ping watchdog so watchdog triggers. Could that be the issue? Would disabling watchdog make it work? Have tested with latest dev version and homing works normal.

**Comment by strips** [comment]
I'll give it a go. As I finally have dual Z max endstops I want to test them :) So I'm loath to go back to Marlin or the stable Repetier branch :)

**Comment by strips** [comment]
Just compiled and upladed, only change was disabled watchdog. Still same.

Made a video of homing from display menu: https://photos.google.com/share/AF1QipOMbcAOhMmVyMfoF767l8f96esoa8LdQkKXPWh26KKNvxw6SaYmRsaWifj4_ULrVg/photo/AF1QipNUKalqTPTR1kcdlG0_2QU6q903qmY5pPzQS8mQ?key=WWJWMTUtaXFteGlkb0NUalNCQU5RbEdCRzFBcXV3

There are some strange artefacts ort moves when homing. I'm talking about the extra moves it does. Is this normal?

**Comment by repetier** [comment]
I see no unneeded moves. Homing does a lot of moves for retesting and activating extruder offset.

Only untypical is the reset, which I can not say why or exactly when it happens. That would require debugging on your system with some test outputs to find the code part where reset happens. Maybe starting in void Printer::homeZAxis() // Cartesian homing

You would write something like this
Com::printFLN(PSTR("DB1"));HAL::delayMilliseconds(5);

with DB1 changing to DB2 ... at several places. That in host log you will see what point got reached and what not. The delay is to give time for sending output to host before starting crash point.

**Comment by strips** [comment]
Thanks, I'll try to locate where that is and start instrumenting the code :)

**Comment by strips** [comment]
I got it working . I wasn't getting anywhere and I decided to start from scratch. So not sure about this one. Maybe something in the config or intermittently wrong.

Thanks for your help.
