### ISSUE TITLE
step_mm failure

### ISSUE THREAD

**Issue by eeerfan** [repetier/Repetier-Firmware#589]
Hi dears
I try to calculate my step_mm in this way:
StepsPerTurn = 400 //my stepper motors are 0.9 degree 
BeltDistance = 2.0mm // GT2 belt 
GroovesInPulley = 10 // FOR ME IS 10
Substepping = 16//for a 1/16 step needed
StepsPerMM = StepsPerTurnSubstepping/(BeltDistanceGroovesInPulley)
= 40016/(2.0*10) =320

it should be noted i use drv8825 stepper motor driver.
but when i add this number for step per mm my printer dosent work correctly.
what can i do???

**Comment by rcarlyle** [comment]
This is not enough information for us to help you troubleshoot, and it pretty clearly isn't a Repetier firmware issue. You should post pictures of your hardware and a description of your troubleshooting steps taken so far on a general help site like the RepRap forum.

**Comment by repetier** [comment]
Did you change it in eeprom or configuration.h? EEPROM would be the right place.
