### ISSUE TITLE
while before } error in ui.cpp

### ISSUE THREAD

**Issue by shaiss** [repetier/Repetier-Firmware#592]
I wanted to try the dev version, but when comping, in the Arduino ide on line 2369, I get an error "expected while before } token".

`#endif
                    for(y = 0; y < UI_ROWS; y++)
                        printRow(y, &cache[y][off[y]], NULL, UI_COLS);
#if UI_DISPLAY_TYPE == DISPLAY_U8G
                    }
                }
#endif
#if UI_DISPLAY_TYPE == DISPLAY_U8G
        } ///<<<Error is marked as here in the IDE
        while( u8g_NextPage(&u8g) );  //end picture loop
#endif
#endif
    Printer::toggleAnimation();
}`

not sure what is causing this as this section seems to be the same as .92

![image](https://cloud.githubusercontent.com/assets/113060/19954003/4550de62-a14a-11e6-97e5-0688dd0f3a98.png)

**Comment by shaiss** [comment]
![image](https://cloud.githubusercontent.com/assets/113060/19954001/3f441c0a-a14a-11e6-8d4a-4f1c39a87b48.png)

**Comment by repetier** [comment]
Only happened when UI_HEAD was not defined. Have uploaded the corrected version. Without UI_HEAD the result is the same with your fix.

**Comment by shaiss** [comment]
Was I supposed to define ui_head somewhere in the configurator tool?   I just used my config.h from .92 and changed some values for v1 like jam detection going high and dual z mins. 

I'll download this new version and try compiling later.

**Comment by shaiss** [comment]
just confirmed that the fw compiles fine now and looked through your last commit.  I'll close this issue out since it resolves the issue.  Will upload to the printer later and confirm.  ty for the hard work!

**Comment by repetier** [comment]
With graphic display you can define UI_HEAD to have a fixed status bar. If you don't you get the old menu style. So not required to define it.
