### ISSUE TITLE
full graphic smart controller failure

### ISSUE THREAD

**Issue by eeerfan** [repetier/Repetier-Firmware#609]
hi dears  @repetier 
when i try to test full graphic smart controller ,i change #define FEATURE_CONTROLLER 11 and add u8g library and upload the code.when lcd start all of things are ok and i can see repetier logo and printer name well but after that i see picture below.but when i use graphical configuration tools on repetier website and i try this firmware  all of thing is completly ok.what is difference between this two code ?
  ![_](https://cloud.githubusercontent.com/assets/22929313/21076207/1107fc08-bf3b-11e6-9c98-3ea4698c8ed4.jpg)

**Comment by repetier** [comment]
Well taht is a good question and seeing that image I see the library is ok. Just when it tries to show the text is does not find it. So I assume you have to much data from too many translations exceeding 64kb and then it is not possible to address it correctly. Please reduce to only a few languages so you see that textdata is below 64kb. I guess then you see the correct chars.
