### ISSUE TITLE
Dual Steppers for X Y and Z Axis

### ISSUE THREAD

**Issue by forReason** [repetier/Repetier-Firmware#613]
Dear Community, I have a Azteeg X3 Pro which allows for up to 8 Stepper Drives.

I build a Large Printer So I want to use two steppers for Each axis (X1/2; Y1/2; Z1/2; E1; E2)
Is this somehow possible? Repetier supports this since months. Unfortunaly they don't bring any updates anymore especially for the newer vici LCD so i would ask for something like that in marlin.

**Comment by repetier** [comment]
What do you mean with new Viki. Viki 2 is supported since it appeared especially for the azteeg X3 Pro.

**Comment by forReason** [comment]
ahh thank you very much. I have overseen the viki 2.
