### ISSUE TITLE
Problems in menu of the RADDS LCD Display 4x20

### ISSUE THREAD

**Issue by Sanitar777** [repetier/Repetier-Firmware#616]
Hello!

I have the following configuration:
Arduino DUE + RADDS + RADDS LCD Display 4x20
H-bot/CoreXY
Repetier-Firmware DEV

When I travel in the menu on the display, I can't go to the previous screen. Missing such an opportunity.
There is no point of return. Refundable only to the main page of display when the timer expires.

Thank you!

**Comment by repetier** [comment]
That is correct. The RADDS Display has a dedicated back button for this (the lower button) so we remove the back option in the menu. Just press back button to go up in menu.

**Comment by Sanitar777** [comment]
Sorry.
Thank you!
