### ISSUE TITLE
EXT0_PREHEAT_TEMP and HEATED_BED_PREHEAT_TEMP blank in current WEB GUI

### ISSUE THREAD

**Issue by Kulitorum** [repetier/Repetier-Firmware#624]
Just downloaded a full source from the web GUI, and HEATED_BED_PREHEAT_TEMP and EXT0_PREHEAT_TEMP currently have no numbers after the defines in config.h

**Comment by repetier** [comment]
Seems like the javascript file got cached. Guess latest website optimization added this. Have now added a version to javascript. After reload it should load load javascript anew.
