### ISSUE TITLE
Ignore fan M106 command missing from recent UI menus in dev

### ISSUE THREAD

**Issue by JBKingdon** [repetier/Repetier-Firmware#630]
Hi,
I suspect this is just a point in time while things are getting changed around, but recent development builds seem to be missing the ignore M106 menu option when using full graphic LCD during print from SD. I rely on that quite a bit, so please can we have it back :)

**Comment by repetier** [comment]
It is now in setup menu and not gone:-)

**Comment by JBKingdon** [comment]
You can't get to the setup menu during a print, which is when I need the ignore M106 command. It needs to go on the new "while printing" menu, beside the option to set a fan speed.

**Comment by JBKingdon** [comment]
I put a copy back in the main menu and it seems to work fine. My usual use-case is while printing I realise that I have completely inappropriate cooling settings and manually set a fan speed that won't be a disaster, and then set ignore M106 to avoid picking up the next bad value in the g-code.

What's the distinction between UI_MENU_ACTIONCOMMAND_FILTER and UI_MENU_ACTIONCOMMAND_FILTER_T? I wasn't quite sure which one to use, but the _T seemed to work ok.

**Comment by repetier** [comment]
For next update I have added it to main menu after fan speeds.

See doc/menustructure.txt for more infos how to make your menu and what the suffixes do. _T is for translated text, means you enter translation id instead of text.

**Comment by JBKingdon** [comment]
Many thanks. Dev is starting to look really good now - great work!
