### ISSUE TITLE
#define ZHOME_X_POS

### ISSUE THREAD

**Issue by Kulitorum** [repetier/Repetier-Firmware#636]
If you set ZHOME_X_POS to 0 in the "Repetier-Firmware configuration tool for version 1.0.0dev" , its written to the config file as:

#define ZHOME_X_POS

(No number after the define) which leads to a compile error

Kulitorum

**Comment by repetier** [comment]
Problem was that the field had a set min value of 1. Have now removed min and seems to work now.
