### ISSUE TITLE
0.92.8 not released als released file and not tagged

### ISSUE THREAD

**Issue by ProfDrYoMan** [repetier/Repetier-Firmware#642]
Hi,
Since 0.92.8 seems to be the last stable release it should be tagged and marked as release?

Sidequestion:
I start using a delta printer (anycubic / kossel). What version should I go for? Dev branch?

**Comment by repetier** [comment]
0.92.9 is latest stable but I would use dev version for the improved and corrected delta behaviours especially regarding probing. Also called dev it is stable.

Tags - ok I forget them from time to time and now I'm past it and do not know where it would need to be inserted. Will try to think for next releases to tag them.

**Comment by ProfDrYoMan** [comment]
Ok.
If I understand you correctly you suggest to use this:
https://www.repetier.com/firmware/dev/index.php
?

**Comment by repetier** [comment]
Exactly, that is what I suggest.

**Comment by ProfDrYoMan** [comment]
Ok. Thank you.
