### ISSUE TITLE
Jam detection filament change and E value

### ISSUE THREAD

**Issue by Kulitorum** [repetier/Repetier-Firmware#644]
After a jam-introduced filament change, the E parameter is reset to zero (I think), resulting in a huge superfast extrude of filament on the first movement after the filament change.

I guess the current E value should be stored before- and restored after the filament change?

Current development branch

Kulitorum

**Comment by Kulitorum** [comment]
Rmpfffhhhh

It stopped happening.....

Kulitorum

**Comment by repetier** [comment]
Since it stopped happening I close the issue.
