### ISSUE TITLE
No definition for Z_UP_AFTER_HOME

### ISSUE THREAD

**Issue by robbycandra** [repetier/Repetier-Firmware#651]
In Printer . cpp : 2050

#if defined(Z_UP_AFTER_HOME) && Z_HOME_DIR < 0
	//PrintLine::moveRelativeDistanceInSteps(0,0,axisStepsPerMM[Z_AXIS]*Z_UP_AFTER_HOME * Z_HOME_DIR,0,homingFeedrate[Z_AXIS],true,false);
	if(zaxis)
		startZ = Z_UP_AFTER_HOME;
#endif

But no definition / declaration for Z_UP_AFTER_HOME in any other place.

**Comment by repetier** [comment]
Will add it in next update to configuration so all can see.
