### ISSUE TITLE
FAST_COREXYZ is never defined

### ISSUE THREAD

**Issue by robbycandra** [repetier/Repetier-Firmware#652]
cannot find " #define FAST_COREXYZ "
but there is " #define GANTRY "

**Comment by jamesarm97** [comment]
I think you just add it to your configuration.h file.

**Comment by repetier** [comment]
Exactly, it is not 100% official so it is not in default config at the moment. Just add it in configuration.h or in manual additions if you use config tool.

**Comment by robbycandra** [comment]
Hi @repetier , I prefer to delete FAST_COREXYZ, because it is same with GANTRY.

**Comment by repetier** [comment]
These variables do completely different things.
GANTRY is autocomputed to test if it is any gantry system.
FAST_COREXYZ says to use nonlinear movement algorithms for improved speed.
