### ISSUE TITLE
DEV version - Compilation error when Babystepping is active

### ISSUE THREAD

**Issue by thiagopeixoto16** [repetier/Repetier-Firmware#678]
DEV version from Git 2017-06-08:

I'm getting this error below when compiling. If I deactivate babystepping the error doesn't show up.
![image](https://user-images.githubusercontent.com/4227271/26953873-5f759c76-4c83-11e7-81b0-4b2b5bce272b.png)

Compiling for RAMPS 1.4 / MEGA2560 on Arduino IDE 1.0.6 and 1.8.3

I'm available for any information required.

Thanks

**Comment by repetier** [comment]
Thanks. Have found th eproblem and fixed it in current release.

**Comment by thiagopeixoto16** [comment]
Tested. Working, Thanks! 👍
