### ISSUE TITLE
A axis?

### ISSUE THREAD

**Issue by Kulitorum** [repetier/Repetier-Firmware#692]
I need to add a fourth axis to repetier firmware, to support nozzle rotation.

How can I do this? - I prefer to new axis to be called "A" but I will settle for another name :)

Thanks.

**Comment by repetier** [comment]
From time to time we get the request for extra axis, but firmware is not prepared for this if it should move together with others. Maybe we add this in version 2.0. If it is ok to move the motor only you can use the extra motordrivers instead and control that motor with G20x commands..

**Comment by Kulitorum** [comment]
Ok, thanks for the reply.

I am installing a duet in the printer.
