### ISSUE TITLE
maxdist?

### ISSUE THREAD

**Issue by Nibbels** [repetier/Repetier-Firmware#696]
About maxdist :
https://github.com/repetier/Repetier-Firmware/blob/development/src/ArduinoAVR/Repetier/Extruder.cpp#L783

within USE_ADVANCE
```
    float maxdist = Extruder::current->maxFeedrate * Extruder::current->maxFeedrate * 0.00013888 / next->maxAcceleration;
    maxdist -= Extruder::current->maxStartFeedrate * Extruder::current->maxStartFeedrate * 0.5 / next->maxAcceleration;
```
I cannot find any use for these two lines of code(?), no further reference.
Is this maybe some relic from old times? Or do I miss something here?

LG

**Comment by repetier** [comment]
No idea what I used that for. I guess it had to do with max. extruder timer frequency, but in any case it is not used any more, so I deleted it for next update. Thanks.
