### ISSUE TITLE
Request: Intelligent cold extrusion prevention

### ISSUE THREAD

**Issue by Highcooley** [repetier/Repetier-Firmware#70]
As I cannot find any cold extrusion prevention settings in the firmware, I assume that there is none implemented yet. How about an intelligent one, which lifts the nozzle away from the part, waits for the hot-end to reach temperature again and resumes printing instead of executing G-code without extrusion. This would generally be cool for the pause and stop function as well, instead of staying in position and cooking the part. Of course, the cold extrusion function would have to give a proper feedback to the host software to make clear why it is pausing.

**Comment by repetier** [comment]
Implemented. User M302 S1 to override prevention.
