### ISSUE TITLE
minor code logic "mimimi"

### ISSUE THREAD

**Issue by Nibbels** [repetier/Repetier-Firmware#701]
https://github.com/repetier/Repetier-Firmware/blob/715eeab43d7ead2326abfeba6ee926e7fe2dbfd4/src/ArduinoAVR/Repetier/SDCard.cpp#L124 
https://github.com/repetier/Repetier-Firmware/blob/715eeab43d7ead2326abfeba6ee926e7fe2dbfd4/src/ArduinoAVR/Repetier/SDCard.cpp#L125
vs.
https://github.com/repetier/Repetier-Firmware/blob/715eeab43d7ead2326abfeba6ee926e7fe2dbfd4/src/ArduinoAVR/Repetier/SDCard.cpp#L126

IF SD_PRINTING then (set PAUSE and SD_PRINTING to false)  ❌ 
followed by
set PAUSE and SD_PRINTING and SD_MOUNTED to false

Dont I get it right or are the lines 124/125 not needed here? btw the other way around?
I guess this might be some relic from old MENU_MODE_SD_PAUSED vs. MENU_MODE_PAUSED

Greetings

**Comment by repetier** [comment]
Yes, no need to test with condition if you later disable even more. Have removed it for next update.
