### ISSUE TITLE
NUM_EXTRUDER + 1 -> PWM_BOARD_FAN 

### ISSUE THREAD

**Issue by Nibbels** [repetier/Repetier-Firmware#703]
https://github.com/repetier/Repetier-Firmware/blob/02ab9059876b651c748cf54b758f2502601b2415/src/ArduinoAVR/Repetier/HAL.cpp#L930

I guess that NUM_EXTRUDER + 1 should be renamed to PWM_BOARD_FAN on both places.

Greetings

**Comment by repetier** [comment]
Also PWM_BOARD_FAN is NUM_EXTRUDER+1 at the moment it should be set to PWM_BOARD_FAN for safety and better readability. Thanks. Will fix it in next update.
