### ISSUE TITLE
[1.0.0dev] "Measure Z-Probe Height" results in wrong measurement if probe is already triggered

### ISSUE THREAD

**Issue by AnukWolf** [repetier/Repetier-Firmware#705]
So I noticed that, when using the aforementioned function,
that everytime I did it after homing (hence Z-probe still being triggered),
the gantry simply moves up two times without going down to measure at all,
and it also results in some really wrong value (~998) to be saved in EEPROM, which is fatal,
as it makes the hotend crash into the heatbed in the next homing procedure.

My config: [Configuration.zip](https://github.com/repetier/Repetier-Firmware/files/1384568/Configuration.zip)

I'd like to see the gantry move up first no matter what, just like it does in the homing procedure, to avoid this situation. Additional safety measures, like ignoring clearly faulty values like 998, could be an option as well.

**Comment by repetier** [comment]
Yes, in deed the result was taken directly without checking for probe error value. Have added a check now.
