### ISSUE TITLE
Is there a way to exit Standby via GCODE?

### ISSUE THREAD

**Issue by andrewsil1** [repetier/Repetier-Firmware#707]
So I'm a little confused about the functionality of the idle timer that puts the entire printer into Standby after a timeout.  It does a great job of turning off the ATX power supply a few minutes after a print in my Felix Tec4, but I have yet to be able to find a way to wake it up by software short of disconnecting/reconnecting the serial connection, which reboots the entire printer.  It seems like since G80 and G81 can be used to issue power off/power on commands, the firmware should respond to power-on via G-Code when in the standby mode, but it doesn't currently seem to do that.

Thoughts?

**Comment by repetier** [comment]
You missed the the commands are M80 and M81 not with G.

Latest firmware version also has AUTOMATIC_POWERUP which when set to 1 will power up automatically. I know felixprinters are working on a update which will contain exactly that automatic power up.
