### ISSUE TITLE
Make puls with different frequency

### ISSUE THREAD

**Issue by eeerfan** [repetier/Repetier-Firmware#708]
Hi Dears
i try to use mksTB6600 step motor driver for my Z axis and Drv8825 step motor driver fo X&Y axises.
but apparently this two kind of driver works with different puls frequency.and now i want make two different puls,one of them for mks driver and another one for drv drivers. i want to now is it possible or no?
and if is possible how can i do it?

**Comment by repetier** [comment]
No, that is not possible and never will. We set all signals in parallel and wait for all drivers to settle pulse, so if you have different requirements, the slowest one is what you have to set.
