### ISSUE TITLE
ATC Semitec 104GT-2 Temptable

### ISSUE THREAD

**Issue by Nibbels** [repetier/Repetier-Firmware#711]
I have been dropping the temptable to Excel and saw some spike.
![screenshot_4](https://user-images.githubusercontent.com/3265671/32150210-1db71d3e-bd10-11e7-8702-44c9f1764d6f.jpg)
222 | 1760

When I drop over Marlins values they dont have this spike:
![screenshot_6](https://user-images.githubusercontent.com/3265671/32150214-2587ac7c-bd10-11e7-96e2-648b148aa042.jpg)

Yes, I know how ridiculous this Issue is, but yeah ..
Might this cause some temperature shift around 210°C till 230°C ? 

Greetings

**Comment by Nibbels** [comment]
Additional Info: 
We have a german thread on this. The source of the need to research this was, because autotune did not work as expected on sensor type 8
http://www.rf1000.de/viewtopic.php?f=23&t=2054&start=40#p20813

;)

**Comment by repetier** [comment]
Thanks for the hint. Have corrected it for next dev update.
