### ISSUE TITLE
I have a strange issue in Z-correction (DEV)

### ISSUE THREAD

**Issue by efiorello** [repetier/Repetier-Firmware#713]
Now the matrix is measured diagonally (before did it increasing z, and then increasing x). The problem is that try to measure 5 points diagonally and the closer you get to the tip of the bed, the z-probe is out of the bed!

you can see the problem in the following log

01:48:08.627 : Z-probe:8.836 X:40.00 Y:0.00
01:48:16.998 : Z-probe:8.565 X:78.75 Y:38.75
01:48:25.479 : Z-probe:8.672 X:117.50 Y:77.50
01:48:33.994 : Z-probe:8.706 X:156.25 Y:116.25
01:48:42.571 : Z-probe:8.763 X:195.00 Y:155.00
01:48:52.351 : Z-probe:8.592 X:78.75 Y:0.00
01:49:00.831 : Z-probe:8.662 X:117.50 Y:38.75
01:49:09.249 : Z-probe:8.620 X:156.25 Y:77.50
01:49:17.937 : Z-probe:8.880 X:195.00 Y:116.25

**Comment by repetier** [comment]
You have set the 3 repefenrence points wrong. They span a parallelogram that can be a aquare if set like described in config tool. P1 must be one edge, P2 point to the right and P3 to the top. You have one of P2/P3 opposite to P1 whcih gives a parallelogram. Change in eeprom.
