### ISSUE TITLE
Repetier online config, dev branch

### ISSUE THREAD

**Issue by PhistterbutInc** [repetier/Repetier-Firmware#715]
The descriptor for decouple test period is listed as such:

    "[s] > Maximum time required to rise temperature by DECOUPLING_TEST_MIN_TEMP_RISE = 1. If rising is slower, heaters will be disabled for safety."

I was under the impression that the variable is in milliseconds not seconds. Could you either verify or correct?

**Comment by repetier** [comment]
Both is correct. The config tool uses seconds and converts it for the written configuration.h into milliseconds.
