### ISSUE TITLE
compile error - #error STEP_DOUBLER_FREQUENCY should be in range 10000-16000.

### ISSUE THREAD

**Issue by sourianos** [repetier/Repetier-Firmware#717]
Arduino IDE 1.8.5
![2017-11-21 17_13_23-repetier - motion cpp _ arduino 1 8 5](https://user-images.githubusercontent.com/8053040/33079888-676feec0-cedf-11e7-97bc-246a8b9c9f41.png) 

Deny compiling due to this error at repetier firmware files v0.92.

exit status 1
#error STEP_DOUBLER_FREQUENCY should be in range 10000-16000.

**Comment by repetier** [comment]
It is no error, it is a sanity check. I bet your STEP_DOUBLER_FREQUENCY value is not in the range 10000-20000 so you try something that the cpu can not handle.

**Comment by Nibbels** [comment]
Whenever there is a bit more code in ISR(TIMER1_COMPA_vect) even 10000 is not a good Idea. -> I have to use 8000-.
(Btw. Double Stepping and Quadstepping seem to work quite well since Halfstepping was removed.)

**Comment by repetier** [comment]
You can simply remove the check if you like. In my tests I could get up to 15000Hz but that was caresian with no delays required. For other systems it might in deed need lower values.

**Comment by sourianos** [comment]
Thank you very much!!!

**Comment by repetier** [comment]
Reduced minimum in current dev.
