### ISSUE TITLE
Using Repetier for laser/cnc without extruder show  extruder menu

### ISSUE THREAD

**Issue by luc-github** [repetier/Repetier-Firmware#720]
Hi, I am trying to setup a laser / cnc  with repetier and it show extruder menu - but I have none, so it is confusing

I have pushed a PR https://github.com/repetier/Repetier-Firmware/pull/719

Hope is it ok 

I think EEPROM export related options and Filament printed length should also be hidden in that case
I can do another PR for this also if it is Ok

**Comment by repetier** [comment]
PR is merged.

You could do it, but please only reduce for the output not creation side. That way hosts do not show unnecessary options but can still set them if needed.

**Comment by luc-github** [comment]
Yes - only to output - I do not want to mess with EEPROM mapping if user change his configuration 

thanks for the confirmation - I will work on it and push it for review later

**Comment by luc-github** [comment]
PR done - https://github.com/repetier/Repetier-Firmware/pull/722
I think I did not missed anything

**Comment by repetier** [comment]
Yes, looks complete. Closing issue. Thanks for improvement.
