### ISSUE TITLE
Compilation error ui.cpp rounding table

### ISSUE THREAD

**Issue by thiagopeixoto16** [repetier/Repetier-Firmware#734]
I got a compilation error on Master due a extra comma here:
![image](https://user-images.githubusercontent.com/4227271/34915740-6fe85274-f912-11e7-9a1e-cea5c83fbb59.png)
Since I'm very dummy with git stuff I'm  hope it helps to solve on repository. I have fixed locally.

**Comment by repetier** [comment]
Thanks. Did not know I had this already in master. Have now moved development to master so it is now fixed.
