### ISSUE TITLE
Config Tool - Trinamic support should populate MICROSTEP_MODES

### ISSUE THREAD

**Issue by alexsomesan** [repetier/Repetier-Firmware#735]
Using the config tool to enable support for DRV_TMC2130 I get a failing build from the resulting configuration, due to missing MICROSTEP_MODES.

For "normal" hardware MICROSTEP_MODES is a parameter of board definitions that support it, but in the case of Trinamic it should be added by the config tool. A board that normally would not support controlling the micro-step setting would be able to do so with Trinamic drivers installed.

**Comment by repetier** [comment]
Ok, have forgotton about the microsteps. Have added them in config tool now.
