### ISSUE TITLE
just a little question

### ISSUE THREAD

**Issue by taalabash** [repetier/Repetier-Firmware#741]
in the last commit "Analog read rewritten, core xyz support" in dev2
i saw that you added 

"#if PRINTER_TYPE == 1" in "PrinterTypeCartesian.cpp"
"#if PRINTER_TYPE == 0" in "PrinterTypeCartesian.h"

"#if PRINTER_TYPE == 0" in "PrinterTypeCoreXYZ.cpp"
"#if PRINTER_TYPE == 1" in "PrinterTypeCoreXYZ.h"

wich is type 1 and wich is type 0 ?
and is the comment written in configuration.h about types numbers true ?

**Comment by repetier** [comment]
I saw I had it wrong and fixed the wrong file :-(

0 = cartesian and 1 = core xyz would be the right combination.

Will upload fixed version once the new temperature conversion is finished.
