### ISSUE TITLE
MKS SBase V1.3 with LCD32 issues with Repetier

### ISSUE THREAD

**Issue by aceranic** [repetier/Repetier-Firmware#742]
I have issue with extruder temp indication in Repetier.
Temp reading is fine on MKS TFT 32 but it is frozen in Repetier. It takes reading when connecting and after that nothing. Stays the same.
Printer is connecting fine and working fine from Repetier.
Anybody have/had same.

**Comment by repetier** [comment]
Where is the temperature reading frozen? Do you have 2 display - mks plus lcd on firmware or is repetier one of our 3 host products?

**Comment by aceranic** [comment]
I have MKS TFT display and reading is good there.
On PC Repetier reading is frozen

**Comment by repetier** [comment]
On PC means repetier-host I assume? Is only reading frozen or does connection not work at all. I mean can you still move it around? Would firmware respond to M119 and report endstop status in log?

**Comment by aceranic** [comment]
Everything is working except temp reading.
M119 is working too

**Comment by repetier** [comment]
Check printer settings. There is a checkbox to enable M105 temperature query. Guess it is simply off so host will not ask for temperatures and you see nothing.

**Comment by aceranic** [comment]
Yes that was it. Thanks a lot
