### ISSUE TITLE
Feature request V2: Add support for Teensy 3.6

### ISSUE THREAD

**Issue by boelle** [repetier/Repetier-Firmware#744]
I wonder if this would be an easy one to add?

Seems like a fast board, and someone has even made a board for it: https://github.com/Flydroid/Teensy-3DPC

will have a look at the board and see if it needs changes

**Comment by repetier** [comment]
It mainly depends on teensy 3.5 or 3.6. That is a different processor then the due so the HAL part will not be compatible. If the arduino are available for it (there are some but not sure for which processors) it would be just adding another hardware package. Maybe it is easier with start otto which might have less compatibility issues and also has 180MHz if it will appear for sale.

**Comment by boelle** [comment]
what will appear for sale? you lost me a bit :-D

**Comment by repetier** [comment]
Arduino Star Otto. Also there are some unboxing videos it seems impossible to order them. At least last time I checked.

**Comment by boelle** [comment]
did a google for it, but like you say hard to find

at least the teensy 3.6 is easy to get
