### ISSUE TITLE
Errors when using MAX6675 in 1.0.1

### ISSUE THREAD

**Issue by overdrive2max** [repetier/Repetier-Firmware#745]
Hi
In version 1.0.1 downloaded via the configuration tool I have found the following errors:

In Extruder.cpp the following errors are present:
Line 2171: "}"
line 2557 and 2559 there are 2 incorrect statements
        max6675_temp[idx] = HAL::spiReceive(0);
Must be 
        max6675_temp[idx] = HAL::spiReceive();

**Comment by repetier** [comment]
Actually this was only an error in HAL version of due not accepting an argument set to default value like the AVR version.

I assume you had this on a due on a due based system.

Github version is fixed and online will follow soon.

**Comment by overdrive2max** [comment]
Jip, Due based board. Was the omitted "}" also fixed?

**Comment by repetier** [comment]
Did not notice this part. I snow also fixed. Thank you.

**Comment by overdrive2max** [comment]
Pleasure.
