### ISSUE TITLE
Tyreus-Lyben not working because method is normalised to 3

### ISSUE THREAD

**Issue by rossiniscarface** [repetier/Repetier-Firmware#751]
Tried to autotune with the new Tyreus-Lyben, but it does not work.
It always returns with Pessen Integral Rule. 

Looking into the Code it is obviouse why:

`void TemperatureController::autotunePID(float temp, uint8_t controllerId, int maxCycles, bool storeValues, int method) {
 if(method < 0) method = 0;
    if(method > 3) method = 3;
`

**Comment by repetier** [comment]
Yes, you are right. Will be fixed in next update. Thanks.
