### ISSUE TITLE
Missing PSTR()

### ISSUE THREAD

**Issue by Nibbels** [repetier/Repetier-Firmware#763]
https://github.com/repetier/Repetier-Firmware/blob/652d86aa5ad778222cab738f4448f6495bb85245/src/ArduinoAVR/Repetier/gcode.cpp#L1171

Is there a PSTR() missing around "Checksum required when switching back to ASCII protocol." ?

Greetings

**Comment by repetier** [comment]
Yes. it is required. Thanks.

**Comment by Nibbels** [comment]
https://github.com/repetier/Repetier-Firmware/commit/5e13879f3efbc8bd1434d63afc5b3f9abffe37d7#diff-8dd44db9d0e927c0e0b17d72fd8158ebL1171
You already fixed and published it.

Therefore I close this Issue.

Thx!!
