### ISSUE TITLE
queueNonlinearMove and sub micro-steps, generate micro-stops

### ISSUE THREAD

**Issue by buf3d** [repetier/Repetier-Firmware#769]
With a delta printer (although the problem is likely to persist in cartesian models), and during the printing of a "vase" type model using the "spiralize" in Cure, i detected some stops (tenths of a second) during the circular movement. Initially I thought it was a problem in the SPI reading speed (we worked with an AVR), but after changing the SPI speed and deactivating the LCD, the problem persisted and in exactly the same points (a little oozing was observed in the final model, during the **micro-stops**).

I have been able to isolate a few lines of gcode where the problem occurs and verify that it persists.
After activating the flags
```
  #define DEBUG_SPLIT
  #define DEBUG_SEGMENT_LENGTH
```

I have found that the gcode line that generates the problem gives the following results:
```
13: 50: 36.304: Segments: 1
13: 50: 36.304: Num lines: 1
13: 50: 36.305: segments_per_line: 1
13: 50: 36.305: Max DS: 0
13: 50: 36.305: Steps Per Segment: 0
13: 50: 36.305: Virtual axis steps: 0
```

   Analyzing the code of the **queueNonlinearMove** function (motion.cpp), even if the line contains 0 steps, it is still added as a PrintLine. I have not investigated more, although I suspect that the optimization of the PrintLines, detects a stretch of non-printing (E steps 0) and the result is a small lost time to change speed between printed and non-printed path.

   I think the right solution is not to add line with steps 0: there is no movement and we avoid processing time and memory consumption (very useful in AVR).

   I have made a modification to check the result:

Original motion.cpp, Line 2019:
```
        int32_t virtualAxisSteps = static_cast <int32_t> (maxStepsPerSegment) * segmentsPerLine;
        if (virtualAxisSteps == 0 && p-> delta [E_AXIS] == 0) {
            if (numLines! = 1) {
                Com :: printErrorFLN (Com :: tDBGDeltaNoMoveinDSegment);
                return false; // Line too short in low precision area
            } 
        }

```
Modified motion.cpp:
```
        int32_t virtualAxisSteps = static_cast <int32_t> (maxStepsPerSegment) * segmentsPerLine;
        if (virtualAxisSteps == 0 && p-> delta [E_AXIS] == 0) {
            if (numLines! = 1) {
                Com :: printErrorFLN (Com :: tDBGDeltaNoMoveinDSegment);
                return false; // Line too short in low precision area
            } else break; // ignore this movement
        }
```

The result is good. We do not have the previous micro-stops.

**Comment by repetier** [comment]
Ok have added this for next update.

In fact you found a very rare case where the move in xy space had some steps while in transformed coordinates there is no move. But you are right that adding such a move is waste of time and should be removed.

Having spiral mode causes lots of small moves increasing the likelyhood of something like that happening. So good point. Thanks.
