### ISSUE TITLE
Is there a way to read the fan speed?

### ISSUE THREAD

**Issue by luxarts** [repetier/Repetier-Firmware#794]
I'm working on an intelligent system and I need to read the current value of the layer fan speed (pwm value or percentage). Is there a way to get it? Can be implemented a M command to return this value?

Thanks!

**Comment by luc-github** [comment]
M408 give the info in JSON format

**Comment by repetier** [comment]
Also firmware reports every change with something like
FanSpeed:89
in the output.

**Comment by luxarts** [comment]
Thanks. I didn't know the M408 command.

**Comment by luxarts** [comment]
I tried the M408 command but the printer throw "Unknown command:M408". Tried using S0 to S5 as parameter but still doesn't work. I'm using the ARM firmware version 1.0.2.

**Comment by repetier** [comment]
You need to check the option to add json output, otherwise the command is not included.

**Comment by luxarts** [comment]
Thanks, I'll try tomorrow!
Can I ask you another question?
Is there a way to get the current print status (while printing from SD card) using a command?
Btw, I don't know if you remember but I'm adding the support for TFT LCD display for Due. I don't completely understand the syntax you use for style the menus on the LCD 128x64 so I'm hard coding the pages.

**Comment by repetier** [comment]
For sd print all you can do is query file position with the proper M code, see repetier.ino for the number, something in the twenties.

Firmware has internally some flags for print state, but if you parse M408 you should get them as well I think.

The menu system is difficult with teh structures. For V2 I'm thinking about also hard coding it as it makes later changes much easier.
