### ISSUE TITLE
Wrong filename in SD list 

### ISSUE THREAD

**Issue by luxarts** [repetier/Repetier-Firmware#800]
Hello! I tried to find a solution to this problem looking at the forums but I didn't find it.
I'm using Repetier 1.0.1 in a ArduinoDue and FullGraphics display.

The problem is that some files are displayed with a strange name.
I copied a file multiple times and changed the name adding 1 character from 10 to 15 to see when this error ocurrs but for my surprise, the 14 characters file (really 14 from name + .gcode =20) is displayed with error but with 15 characters don't.

This is what I get in the display 
![img_20180627_073340266](https://user-images.githubusercontent.com/16926821/41969417-bf5144f0-79dd-11e8-944a-e7742631c3b3.jpg)

And this is the SD card
![captura](https://user-images.githubusercontent.com/16926821/41969485-ef467b58-79dd-11e8-967c-491430d2fe8a.PNG)

Thanks!

**Comment by repetier** [comment]
The strange filename is filename in 8.3 notation. This is one of the reasons 1.0.2 now uses the new sdfat library. That should handle filenames up to 26 chars (ascii only) correctly.

None the less, apart from showing this as 8.3 it should still work.

**Comment by luxarts** [comment]
Oh, so I'll update to 1.0.2 then.
Thanks!
