### ISSUE TITLE
Auto bed leveling not working

### ISSUE THREAD

**Issue by Diablillowilly** [repetier/Repetier-Firmware#805]
Hi;
I have just installed an inductive sensor to my delta 3d printer (I had before an endstop which switched when the nozzle was "pressed"), but when configuring it, I disabled the setting `Extruder is Z-Probe (EXTRUDER_IS_Z_PROBE) `, because my sensor has got a Y offset of 38mm, and with that option enabled, the g32 command didn't take into accountthe offset, but now, with that setting disabled it happens:

1. The printer homes
2. It the effector moves to the first point around 10-20mm over the bed and starts to lower.
3. The sensor detects the bed
4. It goes up to the next point, but this time it raises about100mm above the bed
5. It goes ok for 3 points
6. At the next, it seems it lowered too much, and causes a crash

I guess it's because it had too much distance to calculate the offset.
I have tried veersions 0.92, 1.00, and dev, but it happens on the 3

Here it is my Configuration.h
https://gist.github.com/Diablillowilly/294ea4bbc2d7c555c30defd8659bc730

The output:

![imagen](https://user-images.githubusercontent.com/30727023/42777901-b6a5bcc4-893b-11e8-89fd-b1fe5d0c37bc.png)

**Comment by repetier** [comment]
As you see you are moving to illegal positions so at first fix that problem. Normal reason is that called positions can not be reached with the given offsets so you need to adjust the probing points.
