### ISSUE TITLE
RepRapDiscount Display (4*20)

### ISSUE THREAD

**Issue by leoheck** [repetier/Repetier-Firmware#814]
After update the firmware to 1.0.x my display shows Z axis with a ???? value in the main screen. It constantly changes from 0.00 (or some value) to ?????. It happens with X and Y in other screens as well. 

**It also shows that even after moving to home.**

I am running it on Ramps 1.4

I can add a picture or a gif later if it is needed.

**Comment by pumpal** [comment]
That means it is not homed. Home it and it will show the actual position.
