### ISSUE TITLE
Layers shifted

### ISSUE THREAD

**Issue by leoheck** [repetier/Repetier-Firmware#820]
I was printing more than 20 hours in a row, and I got this. 

Many layers were shifted. 
The parts were firmly fixed on the heated-bed glass.

Do you have any clue about why this happens, and how to fix it?

The previous job was 3 pieces of the same part that is in the center of this image.
It was the 1st time I tried to print so during so many hours in a row and so many parts together.

![printing_issue_img_20180829_113546](https://user-images.githubusercontent.com/1277920/44803602-47548b80-ab95-11e8-92bc-3514996a3c8a.jpg)

**Comment by Nibbels** [comment]
I dont think this is a firmware issue.

You normally get this effect, when your acceleration or jerk is too high.
Or possibly when you set your acceleration === 0
Or if you didnt use ramp acceleration
Or if your steppers are to weak. -> Amps to low, Stepper to small,
Or if your rails do block/rub somehow.
Or if some of your cables are broken just a bit.

**Comment by leoheck** [comment]
Yes sure. Do you know where I can ask this?

**Comment by repetier** [comment]
Also make sure 
#define ALWAYS_CHECK_ENDSTOPS 0

If you have endstop check enabled a shift can happen if a endstop triggers or gets triggered by crosstalk. This normally shifts away from endstop. But if you have not 2 endstops in x direction it is more likely a physical thing like @Nibbels said. Additional reasons are jerk too high, acceleration too high, travel speed too high. The faster your motor runs the less torque it has.
