### ISSUE TITLE
SdFat Lib 1.0.5 to 1.0.6 patch

### ISSUE THREAD

**Issue by Nibbels** [repetier/Repetier-Firmware#821]
That might be interesting to know:
https://github.com/greiman/SdFat/commit/a713da6cf598fb1db2e2b7f380612c5e928ede93
@greiman put some more work into his project.

Maybe it would be good to cherry pick this commit.
The 1.0.7 commit does not change that much. It is more or less codestyle/copyright and a new option to exclude some stream functionality.

Greetings

**Comment by repetier** [comment]
Thanks for the hint. Have already copied changes and they will be included in next update. 1.0.7 was cosmetic but 1.0.6 had a bug as it seems also it is unclear if we used that code part at all. But better be safe here.
