### ISSUE TITLE
Add Board Support for Fystec F6

### ISSUE THREAD

**Issue by Ahrenfelde** [repetier/Repetier-Firmware#828]
Hey,

please added board support for Fystec F6.

It´s a great board with a lot of nice features vor TMC2130.

Here you find the pins.h for Marlin, maybe it help´s a little bit.

https://wiki.fysetc.com/F6_V1.3/

I try to make my own userpins.h but i faild in a lot of compile errors i dont understand.

Here are my NOT Working file:

[userpins.zip](https://github.com/repetier/Repetier-Firmware/files/2536051/userpins.zip)

**Comment by repetier** [comment]
Ok have added my version in dev version on github (not config tool for now).
The pins on the website and in marlin differ, so I have choosen the ones in marlin hoping it works.

You might also read
https://discuss.toms3d.org/hardware-f6/be-aware-with-chinese-fysetc-tmc2130-t384.html

For tmc you need to configure tmc correctly which can be a bit demanding with all the jumpers. Hope it works that way.

**Comment by Ahrenfelde** [comment]
At the Moment i try to compilie the standart Version from your Config Tool with the changed pins.h it gives one compile error. I think it shoud be "defined" instead of "ENABLED"?! 
With "defined" it works, thank you! I will config now my printer an give you reply.

![error1](https://user-images.githubusercontent.com/10586986/47909247-9c5f9700-de8f-11e8-84f6-0420b3729ae4.png)

**Comment by repetier** [comment]
Ah yes also it could as well be deleted as it get not used at the moment. There is no display config at the moment for that board.

**Comment by repetier** [comment]
And the code is wrong I see,
com->G can not be used for that. Use com->C and hasC for that condition. Condition above also should have hasF and not hasE. Will talk with the author how to best optimize this for future.

**Comment by Ahrenfelde** [comment]
okay now i got the last compile error. When i comment the CS pin of E1 and E2 it can compile.
Something is wrong with the variables. EXT2_ENABLE_PIN and EXT1_ENABLE_PIN is not decalred in this scope.

![error1](https://user-images.githubusercontent.com/10586986/47911449-bc925480-de95-11e8-9350-c3d1f377e59b.png)

**Comment by Ahrenfelde** [comment]
got it. on Configuration.h

just added 
#define EXT1_STEP_PIN ORIG_E1_STEP_PIN
#define EXT2_STEP_PIN ORIG_E2_STEP_PIN

#define EXT1_DIR_PIN ORIG_E1_DIR_PIN
#define EXT2_DIR_PIN ORIG_E2_DIR_PIN

#define EXT1_ENABLE_PIN ORIG_E1_ENABLE_PIN
#define EXT2_ENABLE_PIN ORIG_E2_ENABLE_PIN

now it compile without errors.
BIG Thanks to you repetier! It is unbeliveable how fast you get this support here, very nice!
I will test now.

**Comment by Ahrenfelde** [comment]
It seems to work. Thank you again!

**Comment by repetier** [comment]
Ok have uploaded fixex pins/Commands.cpp to github.

Thanks for the feedback.
