### ISSUE TITLE
Duet board does not connect to a wifi network with hidden SSID

### ISSUE THREAD

**Issue by yannlossouarn** [repetier/Repetier-Firmware#836]
My home wifi AP has a hidden SSID, and it seems impossible to the Duet Wifi to connect to it. When I unhide the SSID, Duet connection works fine.

**Comment by repetier** [comment]
I think you are at the wrong spot as we do not support that board with our firmware, so I guess you are using RepRapFirmware for duet. So you should ask there for support.
