### ISSUE TITLE
Many stale PR's

### ISSUE THREAD

**Issue by badvision** [repetier/Repetier-Firmware#849]
There's some pull requests that have been sitting around for six years.   May I suggest that if a PR isn't going to work out that it just be closed and potentially opened again later if it's still relevant?

**Comment by repetier** [comment]
When I get some more time. Big plan is to close all requests once V2 is stable and complete.

**Comment by badvision** [comment]
👍  I hear that loud and clear!  Best of luck with V2!  Very exciting! 😄
