### ISSUE TITLE
[Feature Request] Marlin on ARM requires DTR be ALWAYS asserted

### ISSUE THREAD

**Issue by gruvin** [repetier/Repetier-Firmware#884]
On Mac (and presumably Windows) the USB DCE implemented by Marlin `bugfix-2.0.x` requires that DTE DTR be always asserted. Without this, Marlin's DCE neither accepts or sends data, even though the port opened successfully, in Repetier Host.

RTS/CTS handshaking is not required or enabled, afaik.

As it happens, this issue does not present itself with Pronterface, which seems to work just fine.

Obviously, the issue could be resolved with changes to Marlin. However, I believe that would require messing with lower level USB device code, which is outside Marlin's normal scope (Arduino DUE Wiring libraries?) Just a guess.

Thanks for your time and ongoing efforts.
Bryan.

**Comment by repetier** [comment]
Is this testable with Arduino Due or which hardware is required to test that.

Have you tested Repetier-Server for Mac? There you can set DTR to be always high.

**Comment by gruvin** [comment]
Sorry I don’t have. ‘DUE. 

However, it also occurs to me that even the Arduino 8bit boards do not require DTR to be pulsed to operate correctly. There is a capacitor in the circuit that causes only a short reset pulse, even when DTR remains high, which usually just happens as a matter of course, when the port opens. You could test that at your end, I presume?

The obvious concern would be breaking existing compatibility but I believe you’d be fine there, unless you know something I don’t about some odd board out there.

I wasn’t aware there was a server app. I’ll check it out when I get home.

Thanks.

**Comment by gruvin** [comment]
OK, home and just activated a trial install of Repetier Server on my Mac. Firstly, what a beautiful bit of software! Looks great and is very smooth in function. Well done!

Connecting and transferring commands successfully to the SKR v1.3 board running Marl bugfix-2.0.x ...

- DTR Low to High works
- DTR High to Low does not work
- DTR Low does not work
- DTR High works

This is exactly as I would expect.

I suppose for maximum compatibility, Repetier Host should have the same DTR options, no? However, is Repetier Host still in active development or are you phasing it out in favour of Repetier Server? Personally, having now experienced it, I would be more than happy to use a local only (no remote control) version of Repetier Server, rather than Repetier Host. It's just that good, imo.

**Comment by repetier** [comment]
Ok, so DTR high is the solution. I know other boards requiring RTS high, DTR low. Arduino 8 bit boards do not care as any change just does a reset. So it is really becoming complicated to serve all with one setting.

Regarding server - no need for external servers. If you want it local only you can tell firewall to not allow exit traffic on 3344. Server is in deed the planned replacement for mac host. It has the same code then windows and linux version, so it does not matter that are not so much mac users. Only thing it really misses is an integrated slicer which is also planned.

Mac host will not get much extension but small changes like dtr problem will still be done some time.

**Comment by gruvin** [comment]
Great stuff. Thanks! 😄
