### ISSUE TITLE
dev2 / v2 - EEPROM seems to be reset on every printer reset?

### ISSUE THREAD

**Issue by kyrreaa** [repetier/Repetier-Firmware#906]
Am I doing something wrong or is dev2 branch eeprom handling currently a bit flakey?
Using Ramps-FD with eeprom attached on I2C0 (was working on 0.92 before I started fiddling with dev2).

**Comment by repetier** [comment]
Did not notice the I2C EEPROM is making problems on the 2 due printers I use for testing. Sure you did not eventually disable eeprom with EEPROM_MODE 0?

**Comment by kyrreaa** [comment]
Not sure what happened but it had to do with read back not validating data. Swapped the prom and lowered io speed and it seems to have helped. Will pinpoint issue further later. Right now I got CoreXYZ fish to fry.

**Comment by kyrreaa** [comment]
Was running old code. Ignore.
