### ISSUE TITLE
dev2 - Max extruder feedrate appears to be ignored

### ISSUE THREAD

**Issue by kyrreaa** [repetier/Repetier-Firmware#908]
With max tool 1 feedrate set to 100mm/s it still defaults to 10mm/s.
Using command M203 E6000 unlocks the speed until reset.
Setting value in eeprom appears to work and reading it back shows new value, but it is not being used.
M360 reports what is in the eeprom and it does not change when using M203.

**Comment by repetier** [comment]
Have you updated your firmware? The problem was fixed at 27.1 commit as far as I know.

**Comment by kyrreaa** [comment]
Thanks, I think I fubared the branch I was working on. somehow I have old dev2. Will update and see.

**Comment by kyrreaa** [comment]
Ahh I figured out what happened. I went back to my older branch as the new one does not work with userpins.h due to a redefine of MOTHERBOARD_USER_DEFINED to MOTHERBOARD_USER_DEFINED_DUE and MOTHERBOARD_USER_DEFINED_AVR while still needing MOTHERBOARD_USER_DEFINED in due/pins.h to include userpins.h hehe.

**Comment by kyrreaa** [comment]
Thanks!

**Comment by repetier** [comment]
Thanks. Found remining MOTHERBOARD_USER_DEFINED and fixed it for next update.
