### ISSUE TITLE
Support for USB Host

### ISSUE THREAD

**Issue by Yatin-Khurana** [repetier/Repetier-Firmware#918]
Hi! is there any plans to implement USB Host support(for Flash Disk/USB Drives) using cheap boards such as USB Host Shield with Arduino MEGA2560 based boards and using already available USB host drivers for Due based boards?

**Comment by repetier** [comment]
You mean to use usb drives instead of sd cards? No. Our solution to better comfort is combining firmware with repetier-server where firmware does only control the printer and all high level stuff is done on server side.

**Comment by kyrreaa** [comment]
I think he means for reading sliced jobs off instead of sd cards.

**Comment by Yatin-Khurana** [comment]
ohhh Okay, Thanks.
