### ISSUE TITLE
Dev2: add M218 function

### ISSUE THREAD

**Issue by GenaUser** [repetier/Repetier-Firmware#992]
Would it be possible to add the Gcode M218 function to allow heads offsets changes directly from a touch screen or from any other interface?

Thank's in advance for analyzing this possibility

**Comment by repetier** [comment]
Oh you were using this firmware with server:-) Go on touch screen to settings->eeprom and you can already change it.

**Comment by GenaUser** [comment]
Yes, I agree with you ;-)
The server solution is useful for many parameters. But when you change the nozzle and need to adjust the offsets, it is not always practical to go to a computer to change the values.
For example, on my printer's touch screen, I cannot use the console for this task, neither the offset menu because they work with the M218 command.
To work around this problem, I have to use a second LCD screen with the Repetier interface to make the corrections

![Console](https://user-images.githubusercontent.com/39191971/95772618-520f0380-0cbd-11eb-95c8-07bb44fc5c83.jpg)


![Offset2](https://user-images.githubusercontent.com/39191971/95772643-5f2bf280-0cbd-11eb-9a2b-d58f402ecbda.jpg)



![Repetier](https://user-images.githubusercontent.com/39191971/95772663-68b55a80-0cbd-11eb-85a9-6070eaa72b16.jpg)

**Comment by repetier** [comment]
I have added M218 marlin style so hope it works now. Only difference is that we do not add echo: before the output.
